/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { map_center$_T } from './map_center$_b.js'
export interface maps_ctx_I {
	map_center$?:map_center$_T
}