/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { confirmModal$_T } from './ConfirmModal/confirmModal$_b.js'
import type { messageModal$_T } from './MessageModal/messageModal$_b.js'
export interface shared_ui_ctx_I {
	confirmModal$?:confirmModal$_T
	messageModal$?:messageModal$_T
}