/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { search_menuitem_a$_T } from './search_menuitem_a$_b.js'
import type { search_menus_menu_payload$_T } from './search_menus_menu_payload$_b.js'
export interface consumer_search_ui_ctx_I {
	search_menuitem_a$?:search_menuitem_a$_T
	search_menus_menu_payload$?:search_menus_menu_payload$_T
}