/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { vibrant_loaded$_T } from './vibrant_loaded$_b.js'
export interface vibrant_ctx_I {
	vibrant_loaded$?:vibrant_loaded$_T
}