export const STEP_ZIPCODE = 'STEP_ZIPCODE'
export const STEP_REST_LIST = 'STEP_REST_LIST'
export const STEP_NEW_REST = 'STEP_NEW_REST'
export const STEP_EMAIL = 'STEP_EMAIL'
export const STEP_VERIFY_PHONE = 'STEP_VERIFY_PHONE'
export const STEP_VERIFY_CODE = 'STEP_VERIFY_CODE'
export const STEP_SUCCESS = 'STEP_SUCCESS'
export const STEP_SET_PASSWORD = 'STEP_SET_PASSWORD'
export const STEP_SENT_EMAIL = 'STEP_SENT_EMAIL'
export const STEP_VERIFY_EMAIL = 'STEP_VERIFY_EMAIL'
export const STEP_ERROR_LINK = 'STEP_ERROR_LINK'
export type STEP_T =
	typeof STEP_ZIPCODE|typeof STEP_REST_LIST|typeof STEP_NEW_REST|typeof STEP_EMAIL|typeof STEP_VERIFY_PHONE
	|typeof STEP_VERIFY_CODE|typeof STEP_SUCCESS|typeof STEP_SET_PASSWORD|typeof STEP_SENT_EMAIL|typeof STEP_VERIFY_EMAIL
	|typeof STEP_ERROR_LINK
