/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { fontawesome_loaded$_T } from './fontawesome_loaded$_b.js'
export interface font_awesome_ctx_I {
	fontawesome_loaded$?:fontawesome_loaded$_T
}