/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { add_order_T } from './add_order_b.js'
import type { add_order_item_T } from './add_order_item_b.js'
import type { add_order_item_request__T } from './add_order_item_request__b.js'
import type { add_order_request__T } from './add_order_request__b.js'
import type { consumer_http_client_T } from './consumer_http_client_b.js'
import type { fetch_get_visible_coupons_T } from './fetch_get_visible_coupons_b.js'
import type { fetch_get_visible_coupons_request__T } from './fetch_get_visible_coupons_request__b.js'
import type { fetch_post_customer_info_T } from './fetch_post_customer_info_b.js'
import type { fetch_post_customer_info_request__T } from './fetch_post_customer_info_request__b.js'
import type { fetch_search_menus_masterheading_T } from './fetch_search_menus_masterheading_b.js'
import type { fetch_search_menus_masterheading_request__T } from './fetch_search_menus_masterheading_request__b.js'
import type { fetch_search_menus_menu_T } from './fetch_search_menus_menu_b.js'
import type { fetch_search_menus_menu_request__T } from './fetch_search_menus_menu_request__b.js'
import type { fetch_search_menus_menuitems_T } from './fetch_search_menus_menuitems_b.js'
import type { fetch_search_menus_menuitems_request__T } from './fetch_search_menus_menuitems_request__b.js'
import type { fetch_search_menus_menuoptions_T } from './fetch_search_menus_menuoptions_b.js'
import type { fetch_search_menus_menuoptions_request__T } from './fetch_search_menus_menuoptions_request__b.js'
import type { fetch_search_menus_menuoptionsize_T } from './fetch_search_menus_menuoptionsize_b.js'
import type { fetch_search_menus_menuoptionsize_request__T } from './fetch_search_menus_menuoptionsize_request__b.js'
import type { goto_login_T } from './goto_login_b.js'
import type { pay_order_T } from './pay_order_b.js'
import type { pay_order_request__T } from './pay_order_request__b.js'
import type { search_menus_T } from './search_menus_b.js'
import type { search_menus_request__T } from './search_menus_request__b.js'
export interface consumer_http_ctx_I {
	add_order?:add_order_T
	add_order_item?:add_order_item_T
	add_order_item_request_?:add_order_item_request__T
	add_order_request_?:add_order_request__T
	consumer_http_client?:consumer_http_client_T
	fetch_get_visible_coupons?:fetch_get_visible_coupons_T
	fetch_get_visible_coupons_request_?:fetch_get_visible_coupons_request__T
	fetch_post_customer_info?:fetch_post_customer_info_T
	fetch_post_customer_info_request_?:fetch_post_customer_info_request__T
	fetch_search_menus_masterheading?:fetch_search_menus_masterheading_T
	fetch_search_menus_masterheading_request_?:fetch_search_menus_masterheading_request__T
	fetch_search_menus_menu?:fetch_search_menus_menu_T
	fetch_search_menus_menu_request_?:fetch_search_menus_menu_request__T
	fetch_search_menus_menuitems?:fetch_search_menus_menuitems_T
	fetch_search_menus_menuitems_request_?:fetch_search_menus_menuitems_request__T
	fetch_search_menus_menuoptions?:fetch_search_menus_menuoptions_T
	fetch_search_menus_menuoptions_request_?:fetch_search_menus_menuoptions_request__T
	fetch_search_menus_menuoptionsize?:fetch_search_menus_menuoptionsize_T
	fetch_search_menus_menuoptionsize_request_?:fetch_search_menus_menuoptionsize_request__T
	goto_login?:goto_login_T
	pay_order?:pay_order_T
	pay_order_request_?:pay_order_request__T
	search_menus?:search_menus_T
	search_menus_request_?:search_menus_request__T
}