/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { ro_states$_T } from './ro_states$_b.js'
export interface ro_address_ctx_I {
	ro_states$?:ro_states$_T
}