import type { Geolocatable_I } from '@menus/geolocatable'
import type { schedule_ctx_I } from '@menus/restaurant-hours-lib'
export interface SearchMenuitem_I extends SearchMenuitem_ui_I, Geolocatable_I, schedule_ctx_I {
	RestaurantID:number
	FFID:string
	RestaurantName:string
	Address:string
	ZipCode:string
	Phone:string
	Latitude:string|number
	Longitude:string|number
	Checkout_Message:string
	SegmentID:number
	SegmentName:string
	CuisineID:number
	CuisineName:string
	isDiningIn:boolean
	isCatering:boolean
	isDelivery:boolean
	isPickup:boolean
	MasterheadingID:number
	MasterheadingName:string
	HeadingID:number
	HeadingName:string
	MenuItemID:number
	MenuImageExist:boolean
	RestImageExist:boolean
	MenuItemName:string
	MenuItemDescription:string
	ETA:string
	ETAMin:number
	ETAMax:number
	DeliveryModeID:number
	DeliveryCharge:number
	MinOrder:number
	IsSingleSize:boolean
	PriceLevelID:number
	PriceLevel:string
	Price:number
	IsActualPrice:number
	Distance:string
	ItemCount:number
	ItemOrders:number
	PopularLevel?:number
	SoldOutAction:string
	MenuHour:string
	Availability:string
	IsOpen:boolean
	SortOrder:number
	UTC_OpeningTime:string
	UTC_ClosingTime:string
	MHSortID:0
	HSortID:0
	CuisineFileName:string
	Menus_SourceID:number
	SubscriptionID:number
	IsPlatform:boolean
	MenusServiceFee:number
	PayMenusServiceFee:boolean
	Within_Zone:boolean
	Zone_Range:number
	RestRating:number
	RestRatingCount:number
	WithCoupon:boolean
	CouponCode:string
	CouponDiscount:number
	ShowImageInGallery:boolean
	DishCodeID:number
	Dish:string
	DishFileName:string
	TotalRow:number
	TotalPages:number
	FileName:string
	RestImage:string
	MenuItemImage:string
	cartCount?:number
}
export interface SearchMenuitem_ui_I {
	is_selected:boolean
}
