/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { add_cuisine_T } from './add_cuisine_b.js'
import type { cuisines$_T } from './cuisines$_b.js'
import type { cuisines_busy$_T } from './cuisines_busy$_b.js'
import type { getFirstSelectedCuisineIndex_T } from './getFirstSelectedCuisineIndex_b.js'
import type { remove_cuisine_T } from './remove_cuisine_b.js'
import type { reset_selected_cuisines_T } from './reset_selected_cuisines_b.js'
import type { selected_cuisines$_T } from './selected_cuisines$_b.js'
export interface search_menu_common_ctx_I {
	add_cuisine?:add_cuisine_T
	cuisines$?:cuisines$_T
	cuisines_busy$?:cuisines_busy$_T
	getFirstSelectedCuisineIndex?:getFirstSelectedCuisineIndex_T
	remove_cuisine?:remove_cuisine_T
	reset_selected_cuisines?:reset_selected_cuisines_T
	selected_cuisines$?:selected_cuisines$_T
}