/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { HeadingDetails_goBack_T } from './HeadingDetails/HeadingDetails_goBack_b.js'
import type { MenuitemDetails_activeTab$_T } from './MenuitemDetails_activeTab$_b.js'
import type { OptionGroupSuggestions$_T } from './OptionGroupSuggestions$_b.js'
import type { RoMenuOptionModal_i$_T } from './OptionTab/RoMenuOptionModal_i$_b.js'
import type { SelectOptionCategoryModal_i$_T } from './OptionTab/SelectOptionCategoryModal_i$_b.js'
import type { open_RoMenuOptionModal_i_T } from './OptionTab/open_RoMenuOptionModal_i_b.js'
import type { RoMenuOptionModal_busy$_T } from './RoMenuOptionModal/RoMenuOptionModal_busy$_b.js'
import type { add_ro_menuoptionitem_T } from './RoMenuOptionModal/add_ro_menuoptionitem_b.js'
import type { cancel_ro_menuoptionitem_T } from './RoMenuOptionModal/cancel_ro_menuoptionitem_b.js'
import type { edit_ro_menuoptionitem_T } from './RoMenuOptionModal/edit_ro_menuoptionitem_b.js'
import type { onsort_ro_menuoptionitems_T } from './RoMenuOptionModal/onsort_ro_menuoptionitems_b.js'
import type { ro_menu_ui_API_MENUS_menuoption_del_T } from './RoMenuOptionModal/ro_menu_ui_API_MENUS_menuoption_del_b.js'
import type { ro_menu_ui_API_MENUS_menuoptionitem_del_T } from './RoMenuOptionModal/ro_menu_ui_API_MENUS_menuoptionitem_del_b.js'
import type { toggle_ro_menuoptionitem_Enabled_T } from './RoMenuOptionModal/toggle_ro_menuoptionitem_Enabled_b.js'
import type { create_ro_menuoptionsize_T } from './SizeTab/create_ro_menuoptionsize_b.js'
import type { edit_ro_menuoptionsize_T } from './SizeTab/edit_ro_menuoptionsize_b.js'
import type { isOpen_lookup_ro_menuoptionsizes_section$_T } from './SizeTab/isOpen_lookup_ro_menuoptionsizes_section$_b.js'
import type { menuoptionsize_edit_a$_T } from './SizeTab/menuoptionsize_edit_a$_b.js'
import type { toggle_isOpen_lookup_ro_menuoptionsizes_section_T } from './SizeTab/toggle_isOpen_lookup_ro_menuoptionsizes_section_b.js'
import type { close_ro_menuoptionitem_T } from './close_ro_menuoptionitem_b.js'
import type { lookup_ro_menuoptionsizes$_T } from './lookup_ro_menuoptionsizes$_b.js'
import type { ro_heading$_T } from './ro_heading$_b.js'
import type { ro_masterheadings$_T } from './ro_masterheadings$_b.js'
import type { ro_menu_ui_save_API_MENUS_menuoption_T } from './ro_menu_ui_save_API_MENUS_menuoption_b.js'
import type { ro_menu_ui_save_API_MENUS_menuoptionitem_T } from './ro_menu_ui_save_API_MENUS_menuoptionitem_b.js'
import type { ro_menuitem$_T } from './ro_menuitem$_b.js'
import type { ro_menuitem_is_multisize$_T } from './ro_menuitem_is_multisize$_b.js'
import type { ro_menuitem_is_multisize_errors$_T } from './ro_menuitem_is_multisize_errors$_b.js'
import type { ro_menuitem_is_new_multisize$_T } from './ro_menuitem_is_new_multisize$_b.js'
import type { ro_menuitem_is_new_singlesize$_T } from './ro_menuitem_is_new_singlesize$_b.js'
import type { ro_menuitem_is_new_size_errors$_T } from './ro_menuitem_is_new_size_errors$_b.js'
import type { ro_menuitem_is_new_unselected_size$_T } from './ro_menuitem_is_new_unselected_size$_b.js'
import type { ro_menuitems$_T } from './ro_menuitems$_b.js'
import type { ro_menuoptionitems$_T } from './ro_menuoptionitems$_b.js'
import type { ro_menuoptionitems_limit_option_a$_T } from './ro_menuoptionitems_limit_option_a$_b.js'
import type { ro_menuoptions$_T } from './ro_menuoptions$_b.js'
import type { ro_menuoptionsizes$_T } from './ro_menuoptionsizes$_b.js'
import type { save_ro_menuoptionitem_T } from './save_ro_menuoptionitem_b.js'
import type { selected_ro_masterheading$_T } from './selected_ro_masterheading$_b.js'
import type { selected_ro_menuoption$_T } from './selected_ro_menuoption$_b.js'
import type { set_ro_menuoptionitem_Is_Default_T } from './set_ro_menuoptionitem_Is_Default_b.js'
export interface ro_menu_ui_ctx_I {
	HeadingDetails_goBack?:HeadingDetails_goBack_T
	MenuitemDetails_activeTab$?:MenuitemDetails_activeTab$_T
	OptionGroupSuggestions$?:OptionGroupSuggestions$_T
	RoMenuOptionModal_i$?:RoMenuOptionModal_i$_T
	SelectOptionCategoryModal_i$?:SelectOptionCategoryModal_i$_T
	open_RoMenuOptionModal_i?:open_RoMenuOptionModal_i_T
	RoMenuOptionModal_busy$?:RoMenuOptionModal_busy$_T
	add_ro_menuoptionitem?:add_ro_menuoptionitem_T
	cancel_ro_menuoptionitem?:cancel_ro_menuoptionitem_T
	edit_ro_menuoptionitem?:edit_ro_menuoptionitem_T
	onsort_ro_menuoptionitems?:onsort_ro_menuoptionitems_T
	ro_menu_ui_API_MENUS_menuoption_del?:ro_menu_ui_API_MENUS_menuoption_del_T
	ro_menu_ui_API_MENUS_menuoptionitem_del?:ro_menu_ui_API_MENUS_menuoptionitem_del_T
	toggle_ro_menuoptionitem_Enabled?:toggle_ro_menuoptionitem_Enabled_T
	create_ro_menuoptionsize?:create_ro_menuoptionsize_T
	edit_ro_menuoptionsize?:edit_ro_menuoptionsize_T
	isOpen_lookup_ro_menuoptionsizes_section$?:isOpen_lookup_ro_menuoptionsizes_section$_T
	menuoptionsize_edit_a$?:menuoptionsize_edit_a$_T
	toggle_isOpen_lookup_ro_menuoptionsizes_section?:toggle_isOpen_lookup_ro_menuoptionsizes_section_T
	close_ro_menuoptionitem?:close_ro_menuoptionitem_T
	lookup_ro_menuoptionsizes$?:lookup_ro_menuoptionsizes$_T
	ro_heading$?:ro_heading$_T
	ro_masterheadings$?:ro_masterheadings$_T
	ro_menu_ui_save_API_MENUS_menuoption?:ro_menu_ui_save_API_MENUS_menuoption_T
	ro_menu_ui_save_API_MENUS_menuoptionitem?:ro_menu_ui_save_API_MENUS_menuoptionitem_T
	ro_menuitem$?:ro_menuitem$_T
	ro_menuitem_is_multisize$?:ro_menuitem_is_multisize$_T
	ro_menuitem_is_multisize_errors$?:ro_menuitem_is_multisize_errors$_T
	ro_menuitem_is_new_multisize$?:ro_menuitem_is_new_multisize$_T
	ro_menuitem_is_new_singlesize$?:ro_menuitem_is_new_singlesize$_T
	ro_menuitem_is_new_size_errors$?:ro_menuitem_is_new_size_errors$_T
	ro_menuitem_is_new_unselected_size$?:ro_menuitem_is_new_unselected_size$_T
	ro_menuitems$?:ro_menuitems$_T
	ro_menuoptionitems$?:ro_menuoptionitems$_T
	ro_menuoptionitems_limit_option_a$?:ro_menuoptionitems_limit_option_a$_T
	ro_menuoptions$?:ro_menuoptions$_T
	ro_menuoptionsizes$?:ro_menuoptionsizes$_T
	save_ro_menuoptionitem?:save_ro_menuoptionitem_T
	selected_ro_masterheading$?:selected_ro_masterheading$_T
	selected_ro_menuoption$?:selected_ro_menuoption$_T
	set_ro_menuoptionitem_Is_Default?:set_ro_menuoptionitem_Is_Default_T
}