/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { vanilla_picker_loaded$_T } from './vanilla_picker_loaded$_b.js'
export interface color_ui_ctx_I {
	vanilla_picker_loaded$?:vanilla_picker_loaded$_T
}