/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { device_type$_T } from './MobilePreview/device_type$_b.js'
export interface manage_platform_ui_MobilePreview_ctx_I {
	device_type$?:device_type$_T
}