/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { Signup_email$_T } from './Signup/Signup_email$_b.js'
import type { Signup_fireFlyID$_T } from './Signup/Signup_fireFlyID$_b.js'
import type { Signup_step$_T } from './Signup/Signup_step$_b.js'
import type { Signup_token$_T } from './Signup/Signup_token$_b.js'
import type { Signup_zip_code$_T } from './Signup/Signup_zip_code$_b.js'
import type { continue_restaurant_list_step_T } from './Signup/continue_restaurant_list_step_b.js'
import type { owner_email$_T } from './Signup/owner_email$_b.js'
import type { rest_name$_T } from './Signup/rest_name$_b.js'
import type { rest_phone$_T } from './Signup/rest_phone$_b.js'
import type { selected_rest$_T } from './Signup/selected_rest$_b.js'
import type { verify_signup_token$_T } from './Signup/verify_signup_token$_b.js'
export interface ro_signup_ui_ctx_I {
	Signup_email$?:Signup_email$_T
	Signup_fireFlyID$?:Signup_fireFlyID$_T
	Signup_step$?:Signup_step$_T
	Signup_token$?:Signup_token$_T
	Signup_zip_code$?:Signup_zip_code$_T
	continue_restaurant_list_step?:continue_restaurant_list_step_T
	owner_email$?:owner_email$_T
	rest_name$?:rest_name$_T
	rest_phone$?:rest_phone$_T
	selected_rest$?:selected_rest$_T
	verify_signup_token$?:verify_signup_token$_T
}