/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { close_ro_sideMenuOpened_T } from './close_ro_sideMenuOpened_b.js'
import type { in_ro_sideMenuOpened$_T } from './in_ro_sideMenuOpened$_b.js'
import type { ro_activeTab$_T } from './ro_activeTab$_b.js'
import type { ro_app_body_div$_T } from './ro_app_body_div$_b.js'
import type { ro_app_body_scrollTop$_T } from './ro_app_body_scrollTop$_b.js'
import type { ro_app_body_top_div$_T } from './ro_app_body_top_div$_b.js'
import type { ro_logout_T } from './ro_logout_b.js'
import type { ro_scrollTop$_T } from './ro_scrollTop$_b.js'
import type { ro_selected_tab$_T } from './ro_selected_tab$_b.js'
import type { ro_sideMenuOpened$_T } from './ro_sideMenuOpened$_b.js'
import type { toggle_ro_sideMenuOpened_T } from './toggle_ro_sideMenuOpened_b.js'
export interface ro_layout_ui_ctx_I {
	close_ro_sideMenuOpened?:close_ro_sideMenuOpened_T
	in_ro_sideMenuOpened$?:in_ro_sideMenuOpened$_T
	ro_activeTab$?:ro_activeTab$_T
	ro_app_body_div$?:ro_app_body_div$_T
	ro_app_body_scrollTop$?:ro_app_body_scrollTop$_T
	ro_app_body_top_div$?:ro_app_body_top_div$_T
	ro_logout?:ro_logout_T
	ro_scrollTop$?:ro_scrollTop$_T
	ro_selected_tab$?:ro_selected_tab$_T
	ro_sideMenuOpened$?:ro_sideMenuOpened$_T
	toggle_ro_sideMenuOpened?:toggle_ro_sideMenuOpened_T
}