/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { hidden_route_a_T } from './hidden_route_a_b.js'
import type { hidden_route_regex_a_T } from './hidden_route_regex_a_b.js'
import type { hide_route_T } from './hide_route_b.js'
import type { hide_route_regex_T } from './hide_route_regex_b.js'
import type { is_route_hidden_T } from './is_route_hidden_b.js'
import type { url_friendly_names$_T } from './url_friendly_names$_b.js'
import type { url_regex_friendly_names$_T } from './url_regex_friendly_names$_b.js'
export interface breadcrumb_ctx_I {
	hidden_route_a?:hidden_route_a_T
	hidden_route_regex_a?:hidden_route_regex_a_T
	hide_route?:hide_route_T
	hide_route_regex?:hide_route_regex_T
	is_route_hidden?:is_route_hidden_T
	url_friendly_names$?:url_friendly_names$_T
	url_regex_friendly_names$?:url_regex_friendly_names$_T
}