/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { goto_order_details_T } from './goto_order_details_b.js'
import type { ro_orders_API_ORDERS_list_payload$_T } from './ro_orders_API_ORDERS_list_payload$_b.js'
import type { ro_orders_OrderList_a$_T } from './ro_orders_OrderList_a$_b.js'
import type { ro_orders_Pagination$_T } from './ro_orders_Pagination$_b.js'
import type { ro_orders_TotalRow$_T } from './ro_orders_TotalRow$_b.js'
import type { ro_orders_UnRead$_T } from './ro_orders_UnRead$_b.js'
import type { ro_orders_export_url$_T } from './ro_orders_export_url$_b.js'
import type { ro_orders_filter_date_range$_T } from './ro_orders_filter_date_range$_b.js'
import type { ro_orders_filter_order_StatusID$_T } from './ro_orders_filter_order_StatusID$_b.js'
import type { ro_orders_filter_orders_date_range$_T } from './ro_orders_filter_orders_date_range$_b.js'
import type { ro_orders_filter_serviceTypeId$_T } from './ro_orders_filter_serviceTypeId$_b.js'
import type { ro_orders_last_requestData$_T } from './ro_orders_last_requestData$_b.js'
import type { ro_orders_latest_top_order$_T } from './ro_orders_latest_top_order$_b.js'
import type { ro_orders_ordersSearch$_T } from './ro_orders_ordersSearch$_b.js'
import type { ro_orders_orders_tab_page$_T } from './ro_orders_orders_tab_page$_b.js'
import type { ro_orders_search$_T } from './ro_orders_search$_b.js'
export interface ro_orders_ctx_I {
	goto_order_details?:goto_order_details_T
	ro_orders_API_ORDERS_list_payload$?:ro_orders_API_ORDERS_list_payload$_T
	ro_orders_OrderList_a$?:ro_orders_OrderList_a$_T
	ro_orders_Pagination$?:ro_orders_Pagination$_T
	ro_orders_TotalRow$?:ro_orders_TotalRow$_T
	ro_orders_UnRead$?:ro_orders_UnRead$_T
	ro_orders_export_url$?:ro_orders_export_url$_T
	ro_orders_filter_date_range$?:ro_orders_filter_date_range$_T
	ro_orders_filter_order_StatusID$?:ro_orders_filter_order_StatusID$_T
	ro_orders_filter_orders_date_range$?:ro_orders_filter_orders_date_range$_T
	ro_orders_filter_serviceTypeId$?:ro_orders_filter_serviceTypeId$_T
	ro_orders_last_requestData$?:ro_orders_last_requestData$_T
	ro_orders_latest_top_order$?:ro_orders_latest_top_order$_T
	ro_orders_ordersSearch$?:ro_orders_ordersSearch$_T
	ro_orders_orders_tab_page$?:ro_orders_orders_tab_page$_T
	ro_orders_search$?:ro_orders_search$_T
}