/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { ChangeAddressModal_i$_T } from './ChangeAddressModal/ChangeAddressModal_i$_b.js'
import type { save_default_userAddress_T } from './save_default_userAddress_b.js'
export interface user_address_ui_ctx_I {
	ChangeAddressModal_i$?:ChangeAddressModal_i$_T
	save_default_userAddress?:save_default_userAddress_T
}