/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { assign_to_query_goto_T } from './assign_to_query_goto_b.js'
import type { assign_to_query_str__T } from './assign_to_query_str__b.js'
import type { consume_page_data$_T } from './consume_page_data$_b.js'
import type { hide_navigating_T } from './hide_navigating_b.js'
import type { is_navigating$_T } from './is_navigating$_b.js'
import type { is_navigating_onclick_T } from './is_navigating_onclick_b.js'
import type { navigating_goto_T } from './navigating_goto_b.js'
import type { page_data$_T } from './page_data$_b.js'
import type { page_title$_T } from './page_title$_b.js'
import type { params_HeadingID$_T } from './params_HeadingID$_b.js'
import type { params_MasterheadingID$_T } from './params_MasterheadingID$_b.js'
import type { params_MenuItemID$_T } from './params_MenuItemID$_b.js'
import type { params_MenuItemID_isNew$_T } from './params_MenuItemID_isNew$_b.js'
import type { params_bounds$_T } from './params_bounds$_b.js'
import type { params_cuisine$_T } from './params_cuisine$_b.js'
import type { params_fireFlyID$_T } from './params_fireFlyID$_b.js'
import type { params_name$_T } from './params_name$_b.js'
import type { params_orderID$_T } from './params_orderID$_b.js'
import type { params_other_fireFlyID$_T } from './params_other_fireFlyID$_b.js'
import type { params_search$_T } from './params_search$_b.js'
import type { params_serviceType$_T } from './params_serviceType$_b.js'
import type { query_cuisineID$_T } from './query_cuisineID$_b.js'
import type { query_cuisineName$_T } from './query_cuisineName$_b.js'
import type { query_delivery_fee_step$_T } from './query_delivery_fee_step$_b.js'
import type { query_email$_T } from './query_email$_b.js'
import type { query_fireFlyID$_T } from './query_fireFlyID$_b.js'
import type { query_fsPage$_T } from './query_fsPage$_b.js'
import type { query_fsPageSize$_T } from './query_fsPageSize$_b.js'
import type { query_is_filters_opened$_T } from './query_is_filters_opened$_b.js'
import type { query_keywords$_T } from './query_keywords$_b.js'
import type { query_lat$_T } from './query_lat$_b.js'
import type { query_lng$_T } from './query_lng$_b.js'
import type { query_max_price$_T } from './query_max_price$_b.js'
import type { query_min_order_step$_T } from './query_min_order_step$_b.js'
import type { query_min_price$_T } from './query_min_price$_b.js'
import type { query_mobile_menu_opened$_T } from './query_mobile_menu_opened$_b.js'
import type { query_page$_T } from './query_page$_b.js'
import type { query_pageSize$_T } from './query_pageSize$_b.js'
import type { query_plan$_T } from './query_plan$_b.js'
import type { query_proximity$_T } from './query_proximity$_b.js'
import type { query_search_keywords$_T } from './query_search_keywords$_b.js'
import type { query_search_view$_T } from './query_search_view$_b.js'
import type { query_serviceType$_T } from './query_serviceType$_b.js'
import type { url$_T } from './url$_b.js'
export interface page_ctx_I {
	assign_to_query_goto?:assign_to_query_goto_T
	assign_to_query_str_?:assign_to_query_str__T
	consume_page_data$?:consume_page_data$_T
	hide_navigating?:hide_navigating_T
	is_navigating$?:is_navigating$_T
	is_navigating_onclick?:is_navigating_onclick_T
	navigating_goto?:navigating_goto_T
	page_data$?:page_data$_T
	page_title$?:page_title$_T
	params_HeadingID$?:params_HeadingID$_T
	params_MasterheadingID$?:params_MasterheadingID$_T
	params_MenuItemID$?:params_MenuItemID$_T
	params_MenuItemID_isNew$?:params_MenuItemID_isNew$_T
	params_bounds$?:params_bounds$_T
	params_cuisine$?:params_cuisine$_T
	params_fireFlyID$?:params_fireFlyID$_T
	params_name$?:params_name$_T
	params_orderID$?:params_orderID$_T
	params_other_fireFlyID$?:params_other_fireFlyID$_T
	params_search$?:params_search$_T
	params_serviceType$?:params_serviceType$_T
	query_cuisineID$?:query_cuisineID$_T
	query_cuisineName$?:query_cuisineName$_T
	query_delivery_fee_step$?:query_delivery_fee_step$_T
	query_email$?:query_email$_T
	query_fireFlyID$?:query_fireFlyID$_T
	query_fsPage$?:query_fsPage$_T
	query_fsPageSize$?:query_fsPageSize$_T
	query_is_filters_opened$?:query_is_filters_opened$_T
	query_keywords$?:query_keywords$_T
	query_lat$?:query_lat$_T
	query_lng$?:query_lng$_T
	query_max_price$?:query_max_price$_T
	query_min_order_step$?:query_min_order_step$_T
	query_min_price$?:query_min_price$_T
	query_mobile_menu_opened$?:query_mobile_menu_opened$_T
	query_page$?:query_page$_T
	query_pageSize$?:query_pageSize$_T
	query_plan$?:query_plan$_T
	query_proximity$?:query_proximity$_T
	query_search_keywords$?:query_search_keywords$_T
	query_search_view$?:query_search_view$_T
	query_serviceType$?:query_serviceType$_T
	url$?:url$_T
}