/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { charts_other_rest_a$_T } from './ChartsTab/charts_other_rest_a$_b.js'
import type { charts_proximity$_T } from './ChartsTab/charts_proximity$_b.js'
export interface ro_restaurant_ui_ChartsTab_ctx_I {
	charts_other_rest_a$?:charts_other_rest_a$_T
	charts_proximity$?:charts_proximity$_T
}