/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { API_RESTAURANT_info_payload$_T } from './API_RESTAURANT_info_payload$_b.js'
import type { ro_restaurant$_T } from './ro_restaurant$_b.js'
export interface ro_restaurant_ctx_I {
	API_RESTAURANT_info_payload$?:API_RESTAURANT_info_payload$_T
	ro_restaurant$?:ro_restaurant$_T
}