import type { RoRestaurant_I } from './RoRestaurant_I.js'
export class RoRestaurant implements RoRestaurant_I {
	public AccountName:string
	public AccountNumber:string
	public Address_1:string
	public Address_2:string
	public AutoAcceptNewOrder:boolean
	public BirthDate:string
	public Braintree_Onboard_Message:string
	public Braintree_Onboard_Status:number
	public BusinessInfo:string
	public CI_Address:string
	public CI_City:string
	public CI_ContactNo:string
	public CI_Email:string
	public CI_FirstName:string
	public CI_LastName:string
	public CI_State:string
	public CI_Title:string
	public CI_Webmaster_Email:string
	public CI_Webmaster_Mobile:string
	public CI_Webmaster_Name:string
	public CI_Webmaster_Phone:string
	public CI_ZipCode:string
	public CallOnNewOrder:boolean
	public CallOnScheduledOrder:boolean
	public CallOnScheduledOrderMinutes = 90
	public City:string
	public Created_By:string
	public Cuisine:string
	public CuisineID:number
	public Date_Created:string
	public Date_Modified:string
	public DeliveryBy:string
	public DeliveryCharge:number
	public DeliveryModeID:number
	public DeliveryTime_Max:number
	public DeliveryTime_Min:number
	public Description:string
	public Email:string
	public EmailOnNewOrder:boolean
	public EmailOnScheduledOrder:boolean
	public EmailOnScheduledOrderMinutes = 90
	public EnableOnlineOrdering:boolean
	public Enabled:boolean
	public Fax:string
	public FaxOnNewOrder:boolean
	public FaxOnScheduledOrder:boolean
	public FaxOnScheduledOrderMinutes = 90
	public FileName:string
	public FireFlyID:string
	public ID:number
	public IsSignedUp:boolean
	public Is_Deleted:boolean
	public Keywords:string
	public Latitude:string
	public LegalName:string
	public Longitude:string
	public ManagedByRestaurantOwner:boolean
	public Menus_Phone:string
	public Menus_RestMode:string
	public MinOrder:number
	public Mobile:string
	public Modified_By:string
	public Name:string
	public NotificationOnScheduledOrder:boolean
	public OrderModeID:number
	public OwnerID:number
	public Owner_NextSubscriptionID:number
	public Owner_NextSubscriptionStartDate:string
	public Phone:string
	public PickupTime_Max:number
	public PickupTime_Min:number
	public ProMinOrder:number
	public RegionID:number
	public RestImageExist:boolean
	public RestRating:number
	public RestRatingCount:number
	public RoutingNumber:string
	public SMSOnNewOrder:boolean
	public SMSOnScheduledOrder:boolean
	public SMSOnScheduledOrderMinutes = 90
	public ST_Catering_Enabled:boolean
	public ST_Delivery_Enabled:boolean
	public ST_DiningIn_Enabled:boolean
	public ST_Pickup_Enabled:boolean
	public ST_RestMode:string
	public Segment:string
	public Show_Checkout_Message:boolean
	public Checkout_Message:string
	public SegmentID:number
	public Sell_Alcohol:boolean
	public ServiceFee:number
	public State:string
	public StateID:number
	public Subscription:string
	public SubscriptionBankInfoComplete:boolean
	public SubscriptionID:number
	public SubscriptionIsActive:boolean
	public SubscriptionTypeID:number
	public Subscription_Expiration:string
	public Subscription_Expired:boolean
	public TIN:string
	public Tax:number
	public Terms:boolean
	public TimeZone:string
	public TimeZoneID:number
	public Units:number
	public WaivedDeliveryCharge:number
	public Website:string|null
	public ZipCode:string
	// ui
	public ConfirmAccountNumber:string
	public customerName:string
	public taxRate:string
	public isHidden:boolean
	public is_selected:boolean
}
