export interface RoRestaurant_I {
	AccountName:string
	AccountNumber:string
	Address_1:string
	Address_2:string
	AutoAcceptNewOrder:boolean
	BirthDate:string
	Braintree_Onboard_Message:string
	Braintree_Onboard_Status:number
	BusinessInfo:string
	CI_Address:string
	CI_City:string
	CI_ContactNo:string
	CI_Email:string
	CI_FirstName:string
	CI_LastName:string
	CI_State:string
	CI_Title:string
	CI_Webmaster_Email:string
	CI_Webmaster_Mobile:string
	CI_Webmaster_Name:string
	CI_Webmaster_Phone:string
	CI_ZipCode:string
	CallOnNewOrder:boolean
	CallOnScheduledOrder:boolean
	CallOnScheduledOrderMinutes:number
	City:string
	Created_By:string
	Cuisine:string
	CuisineID:number
	Date_Created:string
	Date_Modified:string
	DeliveryBy:string
	DeliveryCharge:number
	DeliveryModeID:number
	DeliveryTime_Max:number
	DeliveryTime_Min:number
	Description:string
	Email:string
	EmailOnNewOrder:boolean
	EmailOnScheduledOrder:boolean
	EmailOnScheduledOrderMinutes:number
	EnableOnlineOrdering:boolean
	Enabled:boolean
	Fax:string
	FaxOnNewOrder:boolean
	FaxOnScheduledOrder:boolean
	FaxOnScheduledOrderMinutes:number
	FileName:string
	FireFlyID:string
	ID:number
	IsSignedUp:boolean
	Is_Deleted:boolean
	Keywords:string
	Latitude:string
	LegalName:string
	Longitude:string
	ManagedByRestaurantOwner:boolean
	Menus_Phone:string
	Menus_RestMode:string
	MinOrder:number
	Mobile:string
	Modified_By:string
	Name:string
	NotificationOnScheduledOrder:boolean
	OrderModeID:number
	OwnerID:number
	Owner_NextSubscriptionID:number
	Owner_NextSubscriptionStartDate:string
	Phone:string
	PickupTime_Max:number
	PickupTime_Min:number
	ProMinOrder:number
	RegionID:number
	RestImageExist:boolean
	RestRating:number
	RestRatingCount:number
	RoutingNumber:string
	SMSOnNewOrder:boolean
	SMSOnScheduledOrder:boolean
	SMSOnScheduledOrderMinutes:number
	ST_Catering_Enabled:boolean
	ST_Delivery_Enabled:boolean
	ST_DiningIn_Enabled:boolean
	ST_Pickup_Enabled:boolean
	ST_RestMode:string
	Segment:string
	Show_Checkout_Message:boolean
	Checkout_Message:string
	SegmentID:number
	Sell_Alcohol:boolean
	ServiceFee:number
	State:string
	StateID:number
	Subscription:string
	SubscriptionBankInfoComplete:boolean
	SubscriptionID:number
	SubscriptionIsActive:boolean
	SubscriptionTypeID:number
	Subscription_Expiration:string
	Subscription_Expired:boolean
	TIN:string
	Tax:number
	Terms:boolean
	TimeZone:string
	TimeZoneID:number
	Units:number
	WaivedDeliveryCharge:number
	Website:string|null
	ZipCode:string
	// ui
	ConfirmAccountNumber:string
	customerName:string
	taxRate:string
	isHidden:boolean
	is_selected:boolean
}
