import type { Coupon, Order } from '@menus/shared-order'
import type { ServiceType } from '@menus/service-type-common'
export interface OrderDetail_I extends Order {
	ID:number
	OrderNumber:string
	SubTotal:number
	DeliveryCharge:number
	ServiceFee:number
	RestaurantWaivedFee:number
	Total:number
	Driver_Tip_Percent:number
	Driver_Tip:number
	Owner_ServiceFee_Rate:number
	Owner_DeliveryCharge_Restaurant:number
	Owner_NetAccountCredit:number
	ServiceFee_TransactionFee:number
	GrandTotal:number
	Apartment_Suite:string
	Instructions:string
	Tax_Rate:number
	Tax:number
	Is_Accepted:boolean
	Is_Cancelled_By_Customer:boolean
	Is_Cancelled_By_Restaurant:boolean
	PaymentMethodID:number
	PaymentMethod:string
	OrderDate:string
	CustomerName:string
	ServiceType:ServiceType
	DeliveryModeID:number
	DeliveryMode:string
	DeliveryCompany_Driver_Name:string
	DeliveryCompany_Estimated_Dropoff_Time:string
	DeliveryCompany_Estimated_Pickup_Time:string
	DeliveryCompany_Latitude:string
	DeliveryCompany_Longitude:string
	DeliveryCompany_Name:string
	DeliveryCompany_Phone:string
	DeliveryCompany_Phone_CS:string
	DeliveryCompany_Status:string
	DeliveryAddress:string
	RestaurantAddress:string
	RestPhone:string
	RestEmail:string
	CustomerID:number
	ServiceTypeID:number
	DeliveryAddressID:number
	RestaurantID:number
	Restaurant:string
	AgentID:any
	StatusID:number
	Status:string
	OrderTimeDetails:string
	OrderETA:string
	Owner_SubscriptionID:number
	SubscriptionName:string
	SoldOutAction:string
	Is_Read:boolean
	CouponDetail:Coupon[]
	ORDER_START_ETA:string
	ORDER_START_ACTUAL:string
	ORDER_READY_ETA:string
	ORDER_READY_ACTUAL:string
	ORDER_COMPLETED_ETA:string
	ORDER_COMPLETED_ACTUAL:string
}
