#!/bin/sh
alias ga="git add"
alias gb="git branch"
alias gs="git status"
alias gci="git commit"
alias gco="git checkout"
alias gcom="git checkout master"
alias gdiff="git diff"
alias glfb="git log --format=%B"
alias gfr="git fetch && git rebase"
alias grh="git reset --hard"
alias gsp="git smart-pull"
alias gst="git stash"
alias gsta="git stash apply"
alias hpr="hub pull-request"
