/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { innerWidth$_T } from './innerWidth$_b.js'
import type { innerWidth_gt_SCREEN_MD_MIN$_T } from './innerWidth_gt_SCREEN_MD_MIN$_b.js'
import type { innerWidth_gt_SCREEN_SM_MIN$_T } from './innerWidth_gt_SCREEN_SM_MIN$_b.js'
import type { innerWidth_gt_SCREEN_XS_MIN$_T } from './innerWidth_gt_SCREEN_XS_MIN$_b.js'
import type { innerWidth_lte_SCREEN_MD_MIN$_T } from './innerWidth_lte_SCREEN_MD_MIN$_b.js'
import type { innerWidth_lte_SCREEN_SM_MIN$_T } from './innerWidth_lte_SCREEN_SM_MIN$_b.js'
import type { innerWidth_lte_SCREEN_XS_MIN$_T } from './innerWidth_lte_SCREEN_XS_MIN$_b.js'
export interface dom_ctx_I {
	innerWidth$?:innerWidth$_T
	innerWidth_gt_SCREEN_MD_MIN$?:innerWidth_gt_SCREEN_MD_MIN$_T
	innerWidth_gt_SCREEN_SM_MIN$?:innerWidth_gt_SCREEN_SM_MIN$_T
	innerWidth_gt_SCREEN_XS_MIN$?:innerWidth_gt_SCREEN_XS_MIN$_T
	innerWidth_lte_SCREEN_MD_MIN$?:innerWidth_lte_SCREEN_MD_MIN$_T
	innerWidth_lte_SCREEN_SM_MIN$?:innerWidth_lte_SCREEN_SM_MIN$_T
	innerWidth_lte_SCREEN_XS_MIN$?:innerWidth_lte_SCREEN_XS_MIN$_T
}