/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { APP_VERSION$_T } from './APP_VERSION$_b.js'
import type { APP_VERSION_dirty$_T } from './APP_VERSION_dirty$_b.js'
import type { initial_APP_VERSION$_T } from './initial_APP_VERSION$_b.js'
export interface version_refresh_ui_ctx_I {
	APP_VERSION$?:APP_VERSION$_T
	APP_VERSION_dirty$?:APP_VERSION_dirty$_T
	initial_APP_VERSION$?:initial_APP_VERSION$_T
}