/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { PublicKey$_T } from './PublicKey$_b.js'
import type { api_fetch_T } from './api_fetch_b.js'
import type { consumer_request_url__T } from './consumer_request_url__b.js'
import type { fetch_api_request_T } from './fetch_api_request_b.js'
import type { gps$_T } from './gps$_b.js'
import type { init_gps$_T } from './init_gps$_b.js'
import type { platform_settings$_T } from './platform_settings$_b.js'
import type { refresh_auth_token_T } from './refresh_auth_token_b.js'
import type { shared_request_url__T } from './shared_request_url__b.js'
export interface http_ctx_I {
	PublicKey$?:PublicKey$_T
	api_fetch?:api_fetch_T
	consumer_request_url_?:consumer_request_url__T
	fetch_api_request?:fetch_api_request_T
	gps$?:gps$_T
	init_gps$?:init_gps$_T
	platform_settings$?:platform_settings$_T
	refresh_auth_token?:refresh_auth_token_T
	shared_request_url_?:shared_request_url__T
}