/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { enable_beta_features$_T } from './enable_beta_features$_b.js'
import type { html_scrollTop$_T } from './html_scrollTop$_b.js'
import type { is_mobile_menu_open$_T } from './is_mobile_menu_open$_b.js'
import type { open_modals_set_T } from './open_modals_set_b.js'
import type { toggle_mobile_menu_T } from './toggle_mobile_menu_b.js'
export interface layout_ui_ctx_I {
	enable_beta_features$?:enable_beta_features$_T
	html_scrollTop$?:html_scrollTop$_T
	is_mobile_menu_open$?:is_mobile_menu_open$_T
	open_modals_set?:open_modals_set_T
	toggle_mobile_menu?:toggle_mobile_menu_T
}