/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { aptSuiteNo$_T } from './aptSuiteNo$_b.js'
import type { default_userAddress$_T } from './default_userAddress$_b.js'
import type { has_userAddress$_T } from './has_userAddress$_b.js'
import type { pending_userAddress$_T } from './pending_userAddress$_b.js'
import type { userAddress$_T } from './userAddress$_b.js'
import type { userAddress_a$_T } from './userAddress_a$_b.js'
import type { userAddress_text$_T } from './userAddress_text$_b.js'
export interface consumer_user_address_ctx_I {
	aptSuiteNo$?:aptSuiteNo$_T
	default_userAddress$?:default_userAddress$_T
	has_userAddress$?:has_userAddress$_T
	pending_userAddress$?:pending_userAddress$_T
	userAddress$?:userAddress$_T
	userAddress_a$?:userAddress_a$_T
	userAddress_text$?:userAddress_text$_T
}