/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { forgot_password_email_phone$_T } from './ForgotPassword/forgot_password_email_phone$_b.js'
import type { send_forgot_password_T } from './ForgotPassword/send_forgot_password_b.js'
import type { signup_email$_T } from './signup_email$_b.js'
import type { signup_phone$_T } from './signup_phone$_b.js'
export interface consumer_auth_ui_ctx_I {
	forgot_password_email_phone$?:forgot_password_email_phone$_T
	send_forgot_password?:send_forgot_password_T
	signup_email$?:signup_email$_T
	signup_phone$?:signup_phone$_T
}