/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { availability_ctx$_T } from './availability_ctx$_b.js'
import type { current_day_restaurant_hour$_T } from './current_day_restaurant_hour$_b.js'
import type { restaurant_hours$_T } from './restaurant_hours$_b.js'
import type { restaurant_hours_cache_ctx$_T } from './restaurant_hours_cache_ctx$_b.js'
import type { service_restaurant_hours$_T } from './service_restaurant_hours$_b.js'
export interface restaurant_hours_ctx_I {
	availability_ctx$?:availability_ctx$_T
	current_day_restaurant_hour$?:current_day_restaurant_hour$_T
	restaurant_hours$?:restaurant_hours$_T
	restaurant_hours_cache_ctx$?:restaurant_hours_cache_ctx$_T
	service_restaurant_hours$?:service_restaurant_hours$_T
}