export const DELIVERY_MODE_NO_DELIVERY = 1
export const DELIVERY_MODE_MENUS = 2
export const DELIVERY_MODE_RESTAURANT = 3
export const DELIVERY_MODE_RESTOWNER = 4
export const DELIVERY_MODE_DELIVERY_COMPANY = 5
