export const PRICING_MARKETPLACE = 1
export const PRICING_COMBO = 2
export const PRICING_PLATFORM = 3
export const PRICING_TITLE_MARKETPLACE = 'marketplace'
export const PRICING_TITLE_COMBO = 'combo'
export const PRICING_TITLE_PLATFORM = 'platform'
export const PRICING_ID = {
	[PRICING_TITLE_MARKETPLACE]: PRICING_MARKETPLACE,
	[PRICING_TITLE_PLATFORM]: PRICING_PLATFORM,
	[PRICING_TITLE_COMBO]: PRICING_COMBO,
}
export const PRICING_TITLE = {
	[PRICING_MARKETPLACE]: PRICING_TITLE_MARKETPLACE,
	[PRICING_PLATFORM]: PRICING_TITLE_PLATFORM,
	[PRICING_COMBO]: PRICING_TITLE_COMBO,
}
