import {
	RO_USER_LEVEL_ADMIN, RO_USER_LEVEL_AGENT, RO_USER_LEVEL_AGENT_ADMIN, RO_USER_LEVEL_ENCODER, RO_USER_LEVEL_ENCODING,
	RO_USER_LEVEL_KITCHEN, RO_USER_LEVEL_REST_OWNER, RO_USER_LEVEL_SUPER_ADMIN, RO_USER_LEVEL_USER
} from './RO_USER_LEVEL.js'
export const RO_USER_LEVEL_TITLES = {
	[RO_USER_LEVEL_SUPER_ADMIN]: 'Super Admin',
	[RO_USER_LEVEL_ADMIN]: 'Admin',
	[RO_USER_LEVEL_ENCODER]: 'Encoder',
	[RO_USER_LEVEL_REST_OWNER]: 'Restaurant Owner',
	[RO_USER_LEVEL_USER]: 'Server',
	[RO_USER_LEVEL_ENCODING]: 'Encoding',
	[RO_USER_LEVEL_AGENT_ADMIN]: 'Agent Admin',
	[RO_USER_LEVEL_AGENT]: 'Agent',
	[RO_USER_LEVEL_KITCHEN]: 'Kitchen',
}
