import { RO_USER_LEVEL_KITCHEN, RO_USER_LEVEL_REST_OWNER, RO_USER_LEVEL_USER } from './RO_USER_LEVEL.js'
import { RO_USER_LEVEL_TITLES } from './RO_USER_LEVEL_TITLES.js'
export const RO_USER_LEVEL_LIST = [
	{
		id: RO_USER_LEVEL_REST_OWNER,
		value: RO_USER_LEVEL_TITLES[RO_USER_LEVEL_REST_OWNER],
	},
	{
		id: RO_USER_LEVEL_USER,
		value: RO_USER_LEVEL_TITLES[RO_USER_LEVEL_USER],
	},
	{
		id: RO_USER_LEVEL_KITCHEN,
		value: RO_USER_LEVEL_TITLES[RO_USER_LEVEL_KITCHEN],
	},
]
