/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { active_modal$_T } from './active_modal$_b.js'
import type { onchange_modal_state_T } from './onchange_modal_state_b.js'
import type { open_modal_T } from './open_modal_b.js'
export interface modal_ctx_I {
	active_modal$?:active_modal$_T
	onchange_modal_state?:onchange_modal_state_T
	open_modal?:open_modal_T
}