/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { init_app_T } from './init_app_b.js'
import type { init_app_promise_T } from './init_app_promise_b.js'
import type { init_google_analytics_T } from './init_google_analytics_b.js'
import type { init_google_maps_T } from './init_google_maps_b.js'
import type { init_google_maps_promise_T } from './init_google_maps_promise_b.js'
export interface app_initializer_ctx_I {
	init_app?:init_app_T
	init_app_promise?:init_app_promise_T
	init_google_analytics?:init_google_analytics_T
	init_google_maps?:init_google_maps_T
	init_google_maps_promise?:init_google_maps_promise_T
}
