/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { About_Text$_T } from './About_Text$_b.js'
import type { App_Android_Store_Link$_T } from './App_Android_Store_Link$_b.js'
import type { App_IOS_Store_Link$_T } from './App_IOS_Store_Link$_b.js'
import type { App_Icon$_T } from './App_Icon$_b.js'
import type { App_Logo$_T } from './App_Logo$_b.js'
import type { App_Name$_T } from './App_Name$_b.js'
import type { App_Splash$_T } from './App_Splash$_b.js'
import type { Color_Assertive$_T } from './Color_Assertive$_b.js'
import type { Color_Balanced$_T } from './Color_Balanced$_b.js'
import type { Color_Calm$_T } from './Color_Calm$_b.js'
import type { Color_Gray$_T } from './Color_Gray$_b.js'
import type { Color_Positive$_T } from './Color_Positive$_b.js'
import type { Color_RestMapIcon$_T } from './Color_RestMapIcon$_b.js'
import type { Color_Text1$_T } from './Color_Text1$_b.js'
import type { Color_Text2$_T } from './Color_Text2$_b.js'
import type { Color_Text3$_T } from './Color_Text3$_b.js'
import type { EnableGuestSupportChat$_T } from './EnableGuestSupportChat$_b.js'
import type { EnableLoggedInSupportChat$_T } from './EnableLoggedInSupportChat$_b.js'
import type { Enable_About_Text$_T } from './Enable_About_Text$_b.js'
import type { Enable_Catering$_T } from './Enable_Catering$_b.js'
import type { Enable_Coupons$_T } from './Enable_Coupons$_b.js'
import type { Enable_Cuisine_Filter$_T } from './Enable_Cuisine_Filter$_b.js'
import type { Enable_Delivery$_T } from './Enable_Delivery$_b.js'
import type { Enable_DiningIn$_T } from './Enable_DiningIn$_b.js'
import type { Enable_Dish_Filter$_T } from './Enable_Dish_Filter$_b.js'
import type { Enable_Facebook_Login$_T } from './Enable_Facebook_Login$_b.js'
import type { Enable_Google_Login$_T } from './Enable_Google_Login$_b.js'
import type { Enable_HiWaiter$_T } from './Enable_HiWaiter$_b.js'
import type { Enable_Map_View$_T } from './Enable_Map_View$_b.js'
import type { Enable_Pickup$_T } from './Enable_Pickup$_b.js'
import type { Enable_Points$_T } from './Enable_Points$_b.js'
import type { Enable_Popular_Ribbon$_T } from './Enable_Popular_Ribbon$_b.js'
import type { Enable_Yelp_Count$_T } from './Enable_Yelp_Count$_b.js'
import type { Enable_Yelp_Rating$_T } from './Enable_Yelp_Rating$_b.js'
import type { Google_Analytics_ID$_T } from './Google_Analytics_ID$_b.js'
import type { Google_Maps_Key$_T } from './Google_Maps_Key$_b.js'
import type { IMG_CHECKBOX$_T } from './IMG_CHECKBOX$_b.js'
import type { IMG_CHECKBOX_ACTIVE$_T } from './IMG_CHECKBOX_ACTIVE$_b.js'
import type { IMG_RADIO$_T } from './IMG_RADIO$_b.js'
import type { IMG_RADIO_ACTIVE$_T } from './IMG_RADIO_ACTIVE$_b.js'
import type { PrivacyPolicy$_T } from './PrivacyPolicy$_b.js'
import type { RefundPolicy$_T } from './RefundPolicy$_b.js'
import type { SocialLink_Facebook$_T } from './SocialLink_Facebook$_b.js'
import type { SocialLink_Instagram$_T } from './SocialLink_Instagram$_b.js'
import type { SocialLink_Twitter$_T } from './SocialLink_Twitter$_b.js'
import type { SocialLink_Youtube$_T } from './SocialLink_Youtube$_b.js'
import type { isPlatform$_T } from './isPlatform$_b.js'
import type { platformStyles$_T } from './platformStyles$_b.js'
export interface platform_settings_ctx_I {
	About_Text$?:About_Text$_T
	App_Android_Store_Link$?:App_Android_Store_Link$_T
	App_IOS_Store_Link$?:App_IOS_Store_Link$_T
	App_Icon$?:App_Icon$_T
	App_Logo$?:App_Logo$_T
	App_Name$?:App_Name$_T
	App_Splash$?:App_Splash$_T
	Color_Assertive$?:Color_Assertive$_T
	Color_Balanced$?:Color_Balanced$_T
	Color_Calm$?:Color_Calm$_T
	Color_Gray$?:Color_Gray$_T
	Color_Positive$?:Color_Positive$_T
	Color_RestMapIcon$?:Color_RestMapIcon$_T
	Color_Text1$?:Color_Text1$_T
	Color_Text2$?:Color_Text2$_T
	Color_Text3$?:Color_Text3$_T
	EnableGuestSupportChat$?:EnableGuestSupportChat$_T
	EnableLoggedInSupportChat$?:EnableLoggedInSupportChat$_T
	Enable_About_Text$?:Enable_About_Text$_T
	Enable_Catering$?:Enable_Catering$_T
	Enable_Coupons$?:Enable_Coupons$_T
	Enable_Cuisine_Filter$?:Enable_Cuisine_Filter$_T
	Enable_Delivery$?:Enable_Delivery$_T
	Enable_DiningIn$?:Enable_DiningIn$_T
	Enable_Dish_Filter$?:Enable_Dish_Filter$_T
	Enable_Facebook_Login$?:Enable_Facebook_Login$_T
	Enable_Google_Login$?:Enable_Google_Login$_T
	Enable_HiWaiter$?:Enable_HiWaiter$_T
	Enable_Map_View$?:Enable_Map_View$_T
	Enable_Pickup$?:Enable_Pickup$_T
	Enable_Points$?:Enable_Points$_T
	Enable_Popular_Ribbon$?:Enable_Popular_Ribbon$_T
	Enable_Yelp_Count$?:Enable_Yelp_Count$_T
	Enable_Yelp_Rating$?:Enable_Yelp_Rating$_T
	Google_Analytics_ID$?:Google_Analytics_ID$_T
	Google_Maps_Key$?:Google_Maps_Key$_T
	IMG_CHECKBOX$?:IMG_CHECKBOX$_T
	IMG_CHECKBOX_ACTIVE$?:IMG_CHECKBOX_ACTIVE$_T
	IMG_RADIO$?:IMG_RADIO$_T
	IMG_RADIO_ACTIVE$?:IMG_RADIO_ACTIVE$_T
	PrivacyPolicy$?:PrivacyPolicy$_T
	RefundPolicy$?:RefundPolicy$_T
	SocialLink_Facebook$?:SocialLink_Facebook$_T
	SocialLink_Instagram$?:SocialLink_Instagram$_T
	SocialLink_Twitter$?:SocialLink_Twitter$_T
	SocialLink_Youtube$?:SocialLink_Youtube$_T
	isPlatform$?:isPlatform$_T
	platformStyles$?:platformStyles$_T
}