/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { support_chat_window_hide$_T } from './support_chat_window_hide$_b.js'
import type { support_chat_window_show$_T } from './support_chat_window_show$_b.js'
import type { user_session_support_chat_window_hide$_T } from './user_session_support_chat_window_hide$_b.js'
export interface chat_ctx_I {
	support_chat_window_hide$?:support_chat_window_hide$_T
	support_chat_window_show$?:support_chat_window_show$_T
	user_session_support_chat_window_hide$?:user_session_support_chat_window_hide$_T
}