/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { asset_absolute_path_r_asset_relative_path_async_T } from './asset_absolute_path_r_asset_relative_path_async_b.js'
import type { asset_path_a_async_T } from './asset_path_a_async_b.js'
import type { asset_path_r_client_asset_version_path_async_T } from './asset_path_r_client_asset_version_path_async_b.js'
import type { client_output_dir$_T } from './client_output_dir$_b.js'
import type { client_src_client_version_src_aa_async_T } from './client_src_client_version_src_aa_async_b.js'
import type { client_src_r_client_version_src_a_async_T } from './client_src_r_client_version_src_a_async_b.js'
import type { config_preprocess_async_T } from './config_preprocess_async_b.js'
import type { copy_targets_async_T } from './copy_targets_async_b.js'
import type { copy_targets_rollup_plugin_async_T } from './copy_targets_rollup_plugin_async_b.js'
import type { copy_versioned_targets_async_T } from './copy_versioned_targets_async_b.js'
import type { copy_versioned_targets_rollup_plugin_async_T } from './copy_versioned_targets_rollup_plugin_async_b.js'
import type { dev_T } from './dev_b.js'
import type { env_APP_VERSION$_T } from './env_APP_VERSION$_b.js'
import type { file_copy_targets__T } from './file_copy_targets__b.js'
import type { http_replace_r_async_T } from './http_replace_r_async_b.js'
import type { map_basename_r_client_asset_path_a_async_T } from './map_basename_r_client_asset_path_a_async_b.js'
import type { map_basename_r_client_asset_version_path_a_async_T } from './map_basename_r_client_asset_version_path_a_async_b.js'
import type { mode_T } from './mode_b.js'
import type { node_modules_src_aa_async_T } from './node_modules_src_aa_async_b.js'
import type { node_modules_src_basename_aa_async_T } from './node_modules_src_basename_aa_async_b.js'
import type { replace_r_async_T } from './replace_r_async_b.js'
import type { spa_replace_r_async_T } from './spa_replace_r_async_b.js'
import type { src_client_path_dist_client_path_aa_async_T } from './src_client_path_dist_client_path_aa_async_b.js'
import type { src_client_path_r_dist_client_path_async_T } from './src_client_path_r_dist_client_path_async_b.js'
import type { svelte_preprocess_replace_async_T } from './svelte_preprocess_replace_async_b.js'
import type { svg_preprocess_T } from './svg_preprocess_b.js'
import type { version_config_preprocess_async_T } from './version_config_preprocess_async_b.js'
import type { version_node_modules_src_basename_aa_async_T } from './version_node_modules_src_basename_aa_async_b.js'
import type { version_preprocess_sass_async_T } from './version_preprocess_sass_async_b.js'
import type { version_vurl_async_T } from './version_vurl_async_b.js'
import type { vurl_async_T } from './vurl_async_b.js'
export interface web_build_ctx_I {
	asset_absolute_path_r_asset_relative_path_async?:asset_absolute_path_r_asset_relative_path_async_T
	asset_path_a_async?:asset_path_a_async_T
	asset_path_r_client_asset_version_path_async?:asset_path_r_client_asset_version_path_async_T
	client_output_dir$?:client_output_dir$_T
	client_src_client_version_src_aa_async?:client_src_client_version_src_aa_async_T
	client_src_r_client_version_src_a_async?:client_src_r_client_version_src_a_async_T
	config_preprocess_async?:config_preprocess_async_T
	copy_targets_async?:copy_targets_async_T
	copy_targets_rollup_plugin_async?:copy_targets_rollup_plugin_async_T
	copy_versioned_targets_async?:copy_versioned_targets_async_T
	copy_versioned_targets_rollup_plugin_async?:copy_versioned_targets_rollup_plugin_async_T
	dev?:dev_T
	env_APP_VERSION$?:env_APP_VERSION$_T
	file_copy_targets_?:file_copy_targets__T
	http_replace_r_async?:http_replace_r_async_T
	map_basename_r_client_asset_path_a_async?:map_basename_r_client_asset_path_a_async_T
	map_basename_r_client_asset_version_path_a_async?:map_basename_r_client_asset_version_path_a_async_T
	mode?:mode_T
	node_modules_src_aa_async?:node_modules_src_aa_async_T
	node_modules_src_basename_aa_async?:node_modules_src_basename_aa_async_T
	replace_r_async?:replace_r_async_T
	spa_replace_r_async?:spa_replace_r_async_T
	src_client_path_dist_client_path_aa_async?:src_client_path_dist_client_path_aa_async_T
	src_client_path_r_dist_client_path_async?:src_client_path_r_dist_client_path_async_T
	svelte_preprocess_replace_async?:svelte_preprocess_replace_async_T
	svg_preprocess?:svg_preprocess_T
	version_config_preprocess_async?:version_config_preprocess_async_T
	version_node_modules_src_basename_aa_async?:version_node_modules_src_basename_aa_async_T
	version_preprocess_sass_async?:version_preprocess_sass_async_T
	version_vurl_async?:version_vurl_async_T
	vurl_async?:vurl_async_T
}