/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { social_login_data$_T } from './social_login_data$_b.js'
import type { social_login_data_provider$_T } from './social_login_data_provider$_b.js'
export interface social_login_ctx_I {
	social_login_data$?:social_login_data$_T
	social_login_data_provider$?:social_login_data_provider$_T
}