/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { add_applied_coupon_T } from './add_applied_coupon_b.js'
import type { deliveryNotes$_T } from './deliveryNotes$_b.js'
import type { is_shopping_cart_busy$_T } from './is_shopping_cart_busy$_b.js'
import type { reset_filters_T } from './reset_filters_b.js'
import type { shopping_cart_T } from './shopping_cart_b.js'
import type { shopping_cart_busy_T } from './shopping_cart_busy_b.js'
export interface consumer_shopping_cart_ctx_I {
	add_applied_coupon?:add_applied_coupon_T
	deliveryNotes$?:deliveryNotes$_T
	is_shopping_cart_busy$?:is_shopping_cart_busy$_T
	reset_filters?:reset_filters_T
	shopping_cart?:shopping_cart_T
	shopping_cart_busy?:shopping_cart_busy_T
}