/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { socket_io_loaded$_T } from './socket_io_loaded$_b.js'
export interface socket_io_ctx_I {
	socket_io_loaded$?:socket_io_loaded$_T
}