/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { add_points_T } from './add_points_b.js'
import type { assign_AllowReviewOrderCount_T } from './assign_AllowReviewOrderCount_b.js'
import type { consumer_login_user$_T } from './consumer_login_user$_b.js'
export interface consumer_user_common_ctx_I {
	add_points?:add_points_T
	assign_AllowReviewOrderCount?:assign_AllowReviewOrderCount_T
	consumer_login_user$?:consumer_login_user$_T
}