import type { SearchMenuitem_I } from '@menus/search-menu-common'
export interface Restaurant_I extends SearchMenuitem_I {
	ID:number
	FireFlyID:string
	Name:string
	Title:string
	Keywords:string
	Description:string
	Address_1:string
	Address_2:string
	City:string
	State:string
	Mobile:string
	Fax:string
	Email:string
	CI_FirstName:string
	CI_LastName:string
	CI_Address:string
	CI_City:string
	CI_State:string
	CI_ZipCode:string
	CI_ContactNo:string
	CI_Email:string
	CI_Webmaster_Name:string
	BirthDate:string
	LegalName:string
	AccountName:string
	BusinessInfo:string
	RoutingNumber:string
	AccountNumber:string
	TIN:string
	Tax:number
	EnableOnlineOrdering:boolean
	Enabled:boolean
	// Subscription: string
	SubscriptionID:number
	Owner_NextSubscriptionID:number
	Owner_NextSubscriptionStartDate:string
	DeliveryTime_Min:string
	DeliveryTime_Max:string
	PickupTime_Min:string
	PickupTime_Max:string
	Terms:boolean
	WaivedDeliveryCharge:number
	Cuisine:string
	Segment:string
	ST_Catering_Enabled:boolean
	ST_Delivery_Enabled:boolean
	ST_DiningIn_Enabled:boolean
	ST_Pickup_Enabled:boolean
	CallOnNewOrder:boolean
	EmailOnNewOrder:boolean
	FaxOnNewOrder:boolean
	SMSOnNewOrder:boolean
	AutoAcceptNewOrder:boolean
	CallOnScheduledOrder:boolean
	FaxOnScheduledOrder:boolean
	EmailOnScheduledOrder:boolean
	SMSOnScheduledOrder:boolean
	Braintree_Onboard_Status:number
	Braintree_Onboard_Message:string
	Subscription_Expired:boolean
	Subscription_Expiration:string
	WithMenuSense:number
}
