/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { API_FINANCIAL_report_T } from './API_FINANCIAL_report_b.js'
import type { API_FINANCIAL_statement_T } from './API_FINANCIAL_statement_b.js'
import type { API_GLOBAL_get_T } from './API_GLOBAL_get_b.js'
import type { API_GLOBAL_lookupstate_T } from './API_GLOBAL_lookupstate_b.js'
import type { API_LIST_cuisine_T } from './API_LIST_cuisine_b.js'
import type { API_LIST_segment_T } from './API_LIST_segment_b.js'
import type { API_MENUS_dzone_sort_T } from './API_MENUS_dzone_sort_b.js'
import type { API_MENUS_menu_add_T } from './API_MENUS_menu_add_b.js'
import type { API_MENUS_menu_del_T } from './API_MENUS_menu_del_b.js'
import type { API_MENUS_menu_info_T } from './API_MENUS_menu_info_b.js'
import type { API_MENUS_menu_list_T } from './API_MENUS_menu_list_b.js'
import type { API_MENUS_menu_update_T } from './API_MENUS_menu_update_b.js'
import type { API_MENUS_menuoption_add_T } from './API_MENUS_menuoption_add_b.js'
import type { API_MENUS_menuoption_del_T } from './API_MENUS_menuoption_del_b.js'
import type { API_MENUS_menuoption_sort_T } from './API_MENUS_menuoption_sort_b.js'
import type { API_MENUS_menuoption_update_T } from './API_MENUS_menuoption_update_b.js'
import type { API_MENUS_menuoptionitem_add_T } from './API_MENUS_menuoptionitem_add_b.js'
import type { API_MENUS_menuoptionitem_del_T } from './API_MENUS_menuoptionitem_del_b.js'
import type { API_MENUS_menuoptionitem_list_T } from './API_MENUS_menuoptionitem_list_b.js'
import type { API_MENUS_menuoptionitem_sort_T } from './API_MENUS_menuoptionitem_sort_b.js'
import type { API_MENUS_menuoptionitem_update_T } from './API_MENUS_menuoptionitem_update_b.js'
import type { API_MENUS_sched_add_T } from './API_MENUS_sched_add_b.js'
import type { API_ORDERS_accept_T } from './API_ORDERS_accept_b.js'
import type { API_ORDERS_cancel_T } from './API_ORDERS_cancel_b.js'
import type { API_ORDERS_complete_T } from './API_ORDERS_complete_b.js'
import type { API_ORDERS_detail_T } from './API_ORDERS_detail_b.js'
import type { API_ORDERS_details_update_T } from './API_ORDERS_details_update_b.js'
import type { API_ORDERS_list_T } from './API_ORDERS_list_b.js'
import type { API_ORDERS_list_request__T } from './API_ORDERS_list_request__b.js'
import type { API_ORDERS_ready_T } from './API_ORDERS_ready_b.js'
import type { API_ORDERS_route_T } from './API_ORDERS_route_b.js'
import type { API_ORDERS_start_T } from './API_ORDERS_start_b.js'
import type { API_PLATFORM_IMAGE_T } from './API_PLATFORM_IMAGE_b.js'
import type { API_PLATFORM_IMAGE_icon_del_T } from './API_PLATFORM_IMAGE_icon_del_b.js'
import type { API_PLATFORM_IMAGE_icon_upload_T } from './API_PLATFORM_IMAGE_icon_upload_b.js'
import type { API_PLATFORM_IMAGE_splash_del_T } from './API_PLATFORM_IMAGE_splash_del_b.js'
import type { API_PLATFORM_IMAGE_splash_upload_T } from './API_PLATFORM_IMAGE_splash_upload_b.js'
import type { API_PLATFORM_companies_T } from './API_PLATFORM_companies_b.js'
import type { API_PREVIEW_preview_T } from './API_PREVIEW_preview_b.js'
import type { API_REGISTRATION_register_T } from './API_REGISTRATION_register_b.js'
import type { API_REGISTRATION_resend_T } from './API_REGISTRATION_resend_b.js'
import type { API_REGISTRATION_verify_T } from './API_REGISTRATION_verify_b.js'
import type { API_REGISTRATION_verify_email_T } from './API_REGISTRATION_verify_email_b.js'
import type { API_RESTAURANT_accept_terms_T } from './API_RESTAURANT_accept_terms_b.js'
import type { API_RESTAURANT_account_info_T } from './API_RESTAURANT_account_info_b.js'
import type { API_RESTAURANT_account_update_T } from './API_RESTAURANT_account_update_b.js'
import type { API_RESTAURANT_image_del_T } from './API_RESTAURANT_image_del_b.js'
import type { API_RESTAURANT_image_upload_T } from './API_RESTAURANT_image_upload_b.js'
import type { API_RESTAURANT_list_T } from './API_RESTAURANT_list_b.js'
import type { API_SAVE_INFO_T } from './API_SAVE_INFO_b.js'
import type { API_USER_auth_login_T } from './API_USER_auth_login_b.js'
import type { API_USER_del_T } from './API_USER_del_b.js'
import type { API_USER_list_T } from './API_USER_list_b.js'
import type { API_USER_login_T } from './API_USER_login_b.js'
import type { API_USER_pass_T } from './API_USER_pass_b.js'
import type { API_USER_resendemail_T } from './API_USER_resendemail_b.js'
import type { API_USER_restlist_T } from './API_USER_restlist_b.js'
import type { API_USER_restlist_update_T } from './API_USER_restlist_update_b.js'
import type { API_USER_save_T } from './API_USER_save_b.js'
import type { API_USER_update_terms_T } from './API_USER_update_terms_b.js'
import type { API_USER_usersettings_T } from './API_USER_usersettings_b.js'
import type { fetch_API_MENUS_sched_list_T } from './fetch_API_MENUS_sched_list_b.js'
import type { fetch_API_REGISTRATION_new_T } from './fetch_API_REGISTRATION_new_b.js'
import type { fetch_API_REGISTRATION_search_T } from './fetch_API_REGISTRATION_search_b.js'
import type { fill_login_user_T } from './fill_login_user_b.js'
import type { goto_ro_login_T } from './goto_ro_login_b.js'
import type { ro_fetch_T } from './ro_fetch_b.js'
import type { ro_fetch_url__T } from './ro_fetch_url__b.js'
import type { ro_httpClient_T } from './ro_httpClient_b.js'
import type { ro_request__T } from './ro_request__b.js'
import type { save_API_MENUS_menuoption_T } from './save_API_MENUS_menuoption_b.js'
import type { save_API_MENUS_menuoptionitem_T } from './save_API_MENUS_menuoptionitem_b.js'
import type { watch_API_SAVE_INFO_T } from './watch_API_SAVE_INFO_b.js'
export interface ro_http_ctx_I {
	API_FINANCIAL_report?:API_FINANCIAL_report_T
	API_FINANCIAL_statement?:API_FINANCIAL_statement_T
	API_GLOBAL_get?:API_GLOBAL_get_T
	API_GLOBAL_lookupstate?:API_GLOBAL_lookupstate_T
	API_LIST_cuisine?:API_LIST_cuisine_T
	API_LIST_segment?:API_LIST_segment_T
	API_MENUS_dzone_sort?:API_MENUS_dzone_sort_T
	API_MENUS_menu_add?:API_MENUS_menu_add_T
	API_MENUS_menu_del?:API_MENUS_menu_del_T
	API_MENUS_menu_info?:API_MENUS_menu_info_T
	API_MENUS_menu_list?:API_MENUS_menu_list_T
	API_MENUS_menu_update?:API_MENUS_menu_update_T
	API_MENUS_menuoption_add?:API_MENUS_menuoption_add_T
	API_MENUS_menuoption_del?:API_MENUS_menuoption_del_T
	API_MENUS_menuoption_sort?:API_MENUS_menuoption_sort_T
	API_MENUS_menuoption_update?:API_MENUS_menuoption_update_T
	API_MENUS_menuoptionitem_add?:API_MENUS_menuoptionitem_add_T
	API_MENUS_menuoptionitem_del?:API_MENUS_menuoptionitem_del_T
	API_MENUS_menuoptionitem_list?:API_MENUS_menuoptionitem_list_T
	API_MENUS_menuoptionitem_sort?:API_MENUS_menuoptionitem_sort_T
	API_MENUS_menuoptionitem_update?:API_MENUS_menuoptionitem_update_T
	API_MENUS_sched_add?:API_MENUS_sched_add_T
	API_ORDERS_accept?:API_ORDERS_accept_T
	API_ORDERS_cancel?:API_ORDERS_cancel_T
	API_ORDERS_complete?:API_ORDERS_complete_T
	API_ORDERS_detail?:API_ORDERS_detail_T
	API_ORDERS_details_update?:API_ORDERS_details_update_T
	API_ORDERS_list?:API_ORDERS_list_T
	API_ORDERS_list_request_?:API_ORDERS_list_request__T
	API_ORDERS_ready?:API_ORDERS_ready_T
	API_ORDERS_route?:API_ORDERS_route_T
	API_ORDERS_start?:API_ORDERS_start_T
	API_PLATFORM_IMAGE?:API_PLATFORM_IMAGE_T
	API_PLATFORM_IMAGE_icon_del?:API_PLATFORM_IMAGE_icon_del_T
	API_PLATFORM_IMAGE_icon_upload?:API_PLATFORM_IMAGE_icon_upload_T
	API_PLATFORM_IMAGE_splash_del?:API_PLATFORM_IMAGE_splash_del_T
	API_PLATFORM_IMAGE_splash_upload?:API_PLATFORM_IMAGE_splash_upload_T
	API_PLATFORM_companies?:API_PLATFORM_companies_T
	API_PREVIEW_preview?:API_PREVIEW_preview_T
	API_REGISTRATION_register?:API_REGISTRATION_register_T
	API_REGISTRATION_resend?:API_REGISTRATION_resend_T
	API_REGISTRATION_verify?:API_REGISTRATION_verify_T
	API_REGISTRATION_verify_email?:API_REGISTRATION_verify_email_T
	API_RESTAURANT_accept_terms?:API_RESTAURANT_accept_terms_T
	API_RESTAURANT_account_info?:API_RESTAURANT_account_info_T
	API_RESTAURANT_account_update?:API_RESTAURANT_account_update_T
	API_RESTAURANT_image_del?:API_RESTAURANT_image_del_T
	API_RESTAURANT_image_upload?:API_RESTAURANT_image_upload_T
	API_RESTAURANT_list?:API_RESTAURANT_list_T
	API_SAVE_INFO?:API_SAVE_INFO_T
	API_USER_auth_login?:API_USER_auth_login_T
	API_USER_del?:API_USER_del_T
	API_USER_list?:API_USER_list_T
	API_USER_login?:API_USER_login_T
	API_USER_pass?:API_USER_pass_T
	API_USER_resendemail?:API_USER_resendemail_T
	API_USER_restlist?:API_USER_restlist_T
	API_USER_restlist_update?:API_USER_restlist_update_T
	API_USER_save?:API_USER_save_T
	API_USER_update_terms?:API_USER_update_terms_T
	API_USER_usersettings?:API_USER_usersettings_T
	fetch_API_MENUS_sched_list?:fetch_API_MENUS_sched_list_T
	fetch_API_REGISTRATION_new?:fetch_API_REGISTRATION_new_T
	fetch_API_REGISTRATION_search?:fetch_API_REGISTRATION_search_T
	fill_login_user?:fill_login_user_T
	goto_ro_login?:goto_ro_login_T
	ro_fetch?:ro_fetch_T
	ro_fetch_url_?:ro_fetch_url__T
	ro_httpClient?:ro_httpClient_T
	ro_request_?:ro_request__T
	save_API_MENUS_menuoption?:save_API_MENUS_menuoption_T
	save_API_MENUS_menuoptionitem?:save_API_MENUS_menuoptionitem_T
	watch_API_SAVE_INFO?:watch_API_SAVE_INFO_T
}