/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { auth_code_expired$_T } from './auth_code_expired$_b.js'
import type { ro_auth_code_expired$_T } from './ro_auth_code_expired$_b.js'
export interface auth_ctx_I {
	auth_code_expired$?:auth_code_expired$_T
	ro_auth_code_expired$?:ro_auth_code_expired$_T
}