/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { active_notyf_o_a$_T } from './active_notyf_o_a$_b.js'
import type { notyf_banner_error_map$_T } from './notyf_banner_error_map$_b.js'
import type { notyf_error_T } from './notyf_error_b.js'
import type { notyf_success_T } from './notyf_success_b.js'
import type { notyf_warn_T } from './notyf_warn_b.js'
export interface notyf_ctx_I {
	active_notyf_o_a$?:active_notyf_o_a$_T
	notyf_banner_error_map$?:notyf_banner_error_map$_T
	notyf_error?:notyf_error_T
	notyf_success?:notyf_success_T
	notyf_warn?:notyf_warn_T
}