/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { default_location$_T } from './default_location$_b.js'
import type { validate_userAddress_T } from './validate_userAddress_b.js'
export interface user_address_common_ctx_I {
	default_location$?:default_location$_T
	validate_userAddress?:validate_userAddress_T
}