/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { App_ID$_T } from './App_ID$_b.js'
import type { copy_PublicKey_T } from './copy_PublicKey_b.js'
import type { formatted_App_ID$_T } from './formatted_App_ID$_b.js'
import type { manage_platform_busy$_T } from './manage_platform_busy$_b.js'
import type { manage_platform_isPlatform$_T } from './manage_platform_isPlatform$_b.js'
import type { manage_platform_no_active_restaurant$_T } from './manage_platform_no_active_restaurant$_b.js'
import type { manage_platform_settings$_T } from './manage_platform_settings$_b.js'
import type { manage_platform_settings_save_busy$_T } from './manage_platform_settings_save_busy$_b.js'
import type { platform_companies$_T } from './platform_companies$_b.js'
import type { platform_settings_errors$_T } from './platform_settings_errors$_b.js'
import type { platform_settings_form_errors$_T } from './platform_settings_form_errors$_b.js'
import type { platform_settings_serviceType_errors$_T } from './platform_settings_serviceType_errors$_b.js'
import type { platform_settings_valid$_T } from './platform_settings_valid$_b.js'
import type { restaurant_address_a$_T } from './restaurant_address_a$_b.js'
import type { save_manage_platform_settings_T } from './save_manage_platform_settings_b.js'
import type { selected_platform_company$_T } from './selected_platform_company$_b.js'
import type { selected_restaurant_address$_T } from './selected_restaurant_address$_b.js'
import type { sub_App_ID$_T } from './sub_App_ID$_b.js'
export interface manage_platform_ui_ctx_I {
	App_ID$?:App_ID$_T
	copy_PublicKey?:copy_PublicKey_T
	formatted_App_ID$?:formatted_App_ID$_T
	manage_platform_busy$?:manage_platform_busy$_T
	manage_platform_isPlatform$?:manage_platform_isPlatform$_T
	manage_platform_no_active_restaurant$?:manage_platform_no_active_restaurant$_T
	manage_platform_settings$?:manage_platform_settings$_T
	manage_platform_settings_save_busy$?:manage_platform_settings_save_busy$_T
	platform_companies$?:platform_companies$_T
	platform_settings_errors$?:platform_settings_errors$_T
	platform_settings_form_errors$?:platform_settings_form_errors$_T
	platform_settings_serviceType_errors$?:platform_settings_serviceType_errors$_T
	platform_settings_valid$?:platform_settings_valid$_T
	restaurant_address_a$?:restaurant_address_a$_T
	save_manage_platform_settings?:save_manage_platform_settings_T
	selected_platform_company$?:selected_platform_company$_T
	selected_restaurant_address$?:selected_restaurant_address$_T
	sub_App_ID$?:sub_App_ID$_T
}