/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { filters_changed_count$_T } from './filters_changed_count$_b.js'
import type { is_filters_changed$_T } from './is_filters_changed$_b.js'
export interface filters_ctx_I {
	filters_changed_count$?:filters_changed_count$_T
	is_filters_changed$?:is_filters_changed$_T
}