/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { Restaurant_ServiceTypeNav_ul$_T } from './Restaurant_ServiceTypeNav/Restaurant_ServiceTypeNav_ul$_b.js'
import type { filtered_headings$_T } from './filtered_headings$_b.js'
import type { heading_elements$_T } from './heading_elements$_b.js'
import type { restaurant_MenuoptionsModal$_T } from './restaurant_MenuoptionsModal$_b.js'
import type { restaurant_busy$_T } from './restaurant_busy$_b.js'
import type { restaurant_search_text$_T } from './restaurant_search_text$_b.js'
import type { selected_masterheading$_T } from './selected_masterheading$_b.js'
import type { selected_menuitem$_T } from './selected_menuitem$_b.js'
export interface restaurant_ui_ctx_I {
	Restaurant_ServiceTypeNav_ul$?:Restaurant_ServiceTypeNav_ul$_T
	filtered_headings$?:filtered_headings$_T
	heading_elements$?:heading_elements$_T
	restaurant_MenuoptionsModal$?:restaurant_MenuoptionsModal$_T
	restaurant_busy$?:restaurant_busy$_T
	restaurant_search_text$?:restaurant_search_text$_T
	selected_masterheading$?:selected_masterheading$_T
	selected_menuitem$?:selected_menuitem$_T
}