/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { singleton_component_map$_T } from './singleton_component_map$_b.js'
export interface component_registry_ctx_I {
	singleton_component_map$?:singleton_component_map$_T
}