/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { isDeliverable$_T } from './isDeliverable$_b.js'
import type { serviceType$_T } from './serviceType$_b.js'
import type { serviceType_confirmModal$_T } from './serviceType_confirmModal$_b.js'
export interface service_type_ctx_I {
	isDeliverable$?:isDeliverable$_T
	serviceType$?:serviceType$_T
	serviceType_confirmModal$?:serviceType_confirmModal$_T
}