/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { fetch_get_restaurant_hours_T } from './fetch_get_restaurant_hours_b.js'
import type { fetch_get_restaurant_hours_request__T } from './fetch_get_restaurant_hours_request__b.js'
export interface shared_http_ctx_I {
	fetch_get_restaurant_hours?:fetch_get_restaurant_hours_T
	fetch_get_restaurant_hours_request_?:fetch_get_restaurant_hours_request__T
}