/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { dom_goto$_T } from './dom_goto$_b.js'
import type { get_T } from './get_b.js'
import type { goto_T } from './goto_b.js'
export interface ui_ctx_I {
	dom_goto$?:dom_goto$_T
	get?:get_T
	goto?:goto_T
}