/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { restaurant_frame$_T } from './restaurant_frame$_b.js'
import type { restaurant_frame_in_sync$_T } from './restaurant_frame_in_sync$_b.js'
export interface restaurant_frame_ctx_I {
	restaurant_frame$?:restaurant_frame$_T
	restaurant_frame_in_sync$?:restaurant_frame_in_sync$_T
}