/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { delivery_fee$_T } from './delivery_fee$_b.js'
import type { delivery_fee_step$_T } from './delivery_fee_step$_b.js'
import type { is_filters_opened$_T } from './is_filters_opened$_b.js'
import type { max_price$_T } from './max_price$_b.js'
import type { min_order$_T } from './min_order$_b.js'
import type { min_order_step$_T } from './min_order_step$_b.js'
import type { min_price$_T } from './min_price$_b.js'
import type { proximity$_T } from './proximity$_b.js'
import type { search_keyword_a$_T } from './search_keyword_a$_b.js'
import type { search_view$_T } from './search_view$_b.js'
import type { toggle_filters_opened_T } from './toggle_filters_opened_b.js'
export interface filters_common_ctx_I {
	delivery_fee$?:delivery_fee$_T
	delivery_fee_step$?:delivery_fee_step$_T
	is_filters_opened$?:is_filters_opened$_T
	max_price$?:max_price$_T
	min_order$?:min_order$_T
	min_order_step$?:min_order_step$_T
	min_price$?:min_price$_T
	proximity$?:proximity$_T
	search_keyword_a$?:search_keyword_a$_T
	search_view$?:search_view$_T
	toggle_filters_opened?:toggle_filters_opened_T
}