/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { grecaptcha_loaded$_T } from './grecaptcha_loaded$_b.js'
export interface grecaptcha_ctx_I {
	grecaptcha_loaded$?:grecaptcha_loaded$_T
}