export interface PageSizeList {
	CUSTOMER_REVIEW_PAGINATION_ID:number
	FIN_STATEMENT_PAGINATION_ID:number
	MANAGE_PAYMENTS_PAGINATION_ID:number
	MANAGE_REST_PAGINATION_ID:number
	ORDERS_PAGINATION_ID:number
	USERS_PAGINATION_ID:number
}
