/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { accept_terms$_T } from './accept_terms$_b.js'
import type { is_admin_role$_T } from './is_admin_role$_b.js'
import type { is_agent_role$_T } from './is_agent_role$_b.js'
import type { is_appmaker_role$_T } from './is_appmaker_role$_b.js'
import type { is_kitchen_role$_T } from './is_kitchen_role$_b.js'
import type { is_super_admin_role$_T } from './is_super_admin_role$_b.js'
import type { is_vendor_admin_role$_T } from './is_vendor_admin_role$_b.js'
import type { ro_auth_redirects$_T } from './ro_auth_redirects$_b.js'
import type { ro_auth_rules$_T } from './ro_auth_rules$_b.js'
import type { ro_isLoggedIn$_T } from './ro_isLoggedIn$_b.js'
import type { ro_login_user$_T } from './ro_login_user$_b.js'
import type { ro_login_user_NotificationTone_audio$_T } from './ro_login_user_NotificationTone_audio$_b.js'
import type { ro_login_user_NotificationTone_path$_T } from './ro_login_user_NotificationTone_path$_b.js'
import type { ro_login_user_UserLevel$_T } from './ro_login_user_UserLevel$_b.js'
import type { ro_login_user_UserLevel_title$_T } from './ro_login_user_UserLevel_title$_b.js'
import type { setNotificationTone_T } from './setNotificationTone_b.js'
export interface ro_user_common_ctx_I {
	accept_terms$?:accept_terms$_T
	is_admin_role$?:is_admin_role$_T
	is_agent_role$?:is_agent_role$_T
	is_appmaker_role$?:is_appmaker_role$_T
	is_kitchen_role$?:is_kitchen_role$_T
	is_super_admin_role$?:is_super_admin_role$_T
	is_vendor_admin_role$?:is_vendor_admin_role$_T
	ro_auth_redirects$?:ro_auth_redirects$_T
	ro_auth_rules$?:ro_auth_rules$_T
	ro_isLoggedIn$?:ro_isLoggedIn$_T
	ro_login_user$?:ro_login_user$_T
	ro_login_user_NotificationTone_audio$?:ro_login_user_NotificationTone_audio$_T
	ro_login_user_NotificationTone_path$?:ro_login_user_NotificationTone_path$_T
	ro_login_user_UserLevel$?:ro_login_user_UserLevel$_T
	ro_login_user_UserLevel_title$?:ro_login_user_UserLevel_title$_T
	setNotificationTone?:setNotificationTone_T
}