/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { active_search_dishType_Name_a$_T } from './active_search_dishType_Name_a$_b.js'
import type { active_search_dishTypes$_T } from './active_search_dishTypes$_b.js'
import type { geolocatable_center$_T } from './geolocatable_center$_b.js'
import type { load_cuisines_T } from './load_cuisines_b.js'
import type { search_dishTypes$_T } from './search_dishTypes$_b.js'
import type { search_dish_a$_T } from './search_dish_a$_b.js'
import type { search_dish_requestQuery$_T } from './search_dish_requestQuery$_b.js'
import type { search_menus_menuitems$_T } from './search_menus_menuitems$_b.js'
import type { search_menus_menuitems_page$_T } from './search_menus_menuitems_page$_b.js'
import type { search_menus_menuitems_requestQuery$_T } from './search_menus_menuitems_requestQuery$_b.js'
import type { search_menus_menuitems_sort$_T } from './search_menus_menuitems_sort$_b.js'
import type { search_menus_menuitems_termsinclude$_T } from './search_menus_menuitems_termsinclude$_b.js'
import type { select_cuisine_T } from './select_cuisine_b.js'
export interface search_menu_ctx_I {
	active_search_dishType_Name_a$?:active_search_dishType_Name_a$_T
	active_search_dishTypes$?:active_search_dishTypes$_T
	geolocatable_center$?:geolocatable_center$_T
	load_cuisines?:load_cuisines_T
	search_dishTypes$?:search_dishTypes$_T
	search_dish_a$?:search_dish_a$_T
	search_dish_requestQuery$?:search_dish_requestQuery$_T
	search_menus_menuitems$?:search_menus_menuitems$_T
	search_menus_menuitems_page$?:search_menus_menuitems_page$_T
	search_menus_menuitems_requestQuery$?:search_menus_menuitems_requestQuery$_T
	search_menus_menuitems_sort$?:search_menus_menuitems_sort$_T
	search_menus_menuitems_termsinclude$?:search_menus_menuitems_termsinclude$_T
	select_cuisine?:select_cuisine_T
}