/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { color_palette_picker_modal$_T } from './AppConfiguration/color_palette_picker_modal$_b.js'
import type { copy_palette_color_T } from './AppConfiguration/copy_palette_color_b.js'
import type { get_random_palette_T } from './AppConfiguration/get_random_palette_b.js'
import type { manage_App_Icon$_T } from './AppConfiguration/manage_App_Icon$_b.js'
import type { manage_App_Icon_image_color_a$_T } from './AppConfiguration/manage_App_Icon_image_color_a$_b.js'
import type { manage_App_Icon_palette$_T } from './AppConfiguration/manage_App_Icon_palette$_b.js'
import type { manage_App_Icon_palette_o$_T } from './AppConfiguration/manage_App_Icon_palette_o$_b.js'
import type { manage_App_Icon_src$_T } from './AppConfiguration/manage_App_Icon_src$_b.js'
import type { manage_App_Splash_image_color_a$_T } from './AppConfiguration/manage_App_Splash_image_color_a$_b.js'
import type { manage_App_Splash_palette$_T } from './AppConfiguration/manage_App_Splash_palette$_b.js'
import type { manage_App_Splash_palette_o$_T } from './AppConfiguration/manage_App_Splash_palette_o$_b.js'
import type { manage_App_Splash_src$_T } from './AppConfiguration/manage_App_Splash_src$_b.js'
import type { manage_App_image_errors_ctx$_T } from './AppConfiguration/manage_App_image_errors_ctx$_b.js'
import type { open_color_palette_picker_modal_T } from './AppConfiguration/open_color_palette_picker_modal_b.js'
import type { palette_o__T } from './AppConfiguration/palette_o__b.js'
import type { remove_Image_T } from './AppConfiguration/remove_Image_b.js'
import type { select_palette_T } from './AppConfiguration/select_palette_b.js'
import type { selected_palette_item$_T } from './AppConfiguration/selected_palette_item$_b.js'
import type { shuffle_global_colors_T } from './AppConfiguration/shuffle_global_colors_b.js'
import type { shuffle_map_colors_T } from './AppConfiguration/shuffle_map_colors_b.js'
import type { shuffle_palette_T } from './AppConfiguration/shuffle_palette_b.js'
import type { shuffle_top_navigation_colors_T } from './AppConfiguration/shuffle_top_navigation_colors_b.js'
import type { upload_Image_T } from './AppConfiguration/upload_Image_b.js'
export interface manage_platform_ui_AppConfiguration_ctx_I {
	color_palette_picker_modal$?:color_palette_picker_modal$_T
	copy_palette_color?:copy_palette_color_T
	get_random_palette?:get_random_palette_T
	manage_App_Icon$?:manage_App_Icon$_T
	manage_App_Icon_image_color_a$?:manage_App_Icon_image_color_a$_T
	manage_App_Icon_palette$?:manage_App_Icon_palette$_T
	manage_App_Icon_palette_o$?:manage_App_Icon_palette_o$_T
	manage_App_Icon_src$?:manage_App_Icon_src$_T
	manage_App_Splash_image_color_a$?:manage_App_Splash_image_color_a$_T
	manage_App_Splash_palette$?:manage_App_Splash_palette$_T
	manage_App_Splash_palette_o$?:manage_App_Splash_palette_o$_T
	manage_App_Splash_src$?:manage_App_Splash_src$_T
	manage_App_image_errors_ctx$?:manage_App_image_errors_ctx$_T
	open_color_palette_picker_modal?:open_color_palette_picker_modal_T
	palette_o_?:palette_o__T
	remove_Image?:remove_Image_T
	select_palette?:select_palette_T
	selected_palette_item$?:selected_palette_item$_T
	shuffle_global_colors?:shuffle_global_colors_T
	shuffle_map_colors?:shuffle_map_colors_T
	shuffle_palette?:shuffle_palette_T
	shuffle_top_navigation_colors?:shuffle_top_navigation_colors_T
	upload_Image?:upload_Image_T
}