/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { EditOrder_c_serviceType$_T } from './EditOrder/EditOrder_c_serviceType$_b.js'
export interface ro_orders_ui_ctx_I {
	EditOrder_c_serviceType$?:EditOrder_c_serviceType$_T
}