/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { braintree_apple_pay_loaded$_T } from './braintree_apple_pay_loaded$_b.js'
import type { braintree_loaded$_T } from './braintree_loaded$_b.js'
export interface braintree_ui_ctx_I {
	braintree_apple_pay_loaded$?:braintree_apple_pay_loaded$_T
	braintree_loaded$?:braintree_loaded$_T
}