/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { API_COUPONS_list_payload$_T } from './API_COUPONS_list_payload$_b.js'
import type { API_MENUS_heading_info_payload$_T } from './API_MENUS_heading_info_payload$_b.js'
import type { API_MENUS_heading_list_payload$_T } from './API_MENUS_heading_list_payload$_b.js'
import type { API_MENUS_masterheading_info_payload$_T } from './API_MENUS_masterheading_info_payload$_b.js'
import type { API_MENUS_masterheading_list_payload$_T } from './API_MENUS_masterheading_list_payload$_b.js'
import type { API_MENUS_menu_info_payload$_T } from './API_MENUS_menu_info_payload$_b.js'
import type { API_MENUS_menu_list_payload$_T } from './API_MENUS_menu_list_payload$_b.js'
import type { API_MENUS_menuoption_list_payload$_T } from './API_MENUS_menuoption_list_payload$_b.js'
import type { API_MENUS_menusize_list_payload$_T } from './API_MENUS_menusize_list_payload$_b.js'
import type { API_MENUS_optiongroup_list_payload$_T } from './API_MENUS_optiongroup_list_payload$_b.js'
import type { API_MENUS_sizelookup_payload$_T } from './API_MENUS_sizelookup_payload$_b.js'
import type { API_ORDERS_detail_payload$_T } from './API_ORDERS_detail_payload$_b.js'
import type { coupons$_T } from './coupons$_b.js'
import type { goto_order_edit$_T } from './goto_order_edit$_b.js'
import type { heading_list$_T } from './heading_list$_b.js'
import type { order_info$_T } from './order_info$_b.js'
import type { subscribe_ERR_INVALID_ACCESS_T } from './subscribe_ERR_INVALID_ACCESS_b.js'
export interface ro_restaurant_ui_ctx_I {
	API_COUPONS_list_payload$?:API_COUPONS_list_payload$_T
	API_MENUS_heading_info_payload$?:API_MENUS_heading_info_payload$_T
	API_MENUS_heading_list_payload$?:API_MENUS_heading_list_payload$_T
	API_MENUS_masterheading_info_payload$?:API_MENUS_masterheading_info_payload$_T
	API_MENUS_masterheading_list_payload$?:API_MENUS_masterheading_list_payload$_T
	API_MENUS_menu_info_payload$?:API_MENUS_menu_info_payload$_T
	API_MENUS_menu_list_payload$?:API_MENUS_menu_list_payload$_T
	API_MENUS_menuoption_list_payload$?:API_MENUS_menuoption_list_payload$_T
	API_MENUS_menusize_list_payload$?:API_MENUS_menusize_list_payload$_T
	API_MENUS_optiongroup_list_payload$?:API_MENUS_optiongroup_list_payload$_T
	API_MENUS_sizelookup_payload$?:API_MENUS_sizelookup_payload$_T
	API_ORDERS_detail_payload$?:API_ORDERS_detail_payload$_T
	coupons$?:coupons$_T
	goto_order_edit$?:goto_order_edit$_T
	heading_list$?:heading_list$_T
	order_info$?:order_info$_T
	subscribe_ERR_INVALID_ACCESS?:subscribe_ERR_INVALID_ACCESS_T
}