/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { minute_tick$_T } from './minute_tick$_b.js'
import type { second_tick$_T } from './second_tick$_b.js'
export interface date_ctx_I {
	minute_tick$?:minute_tick$_T
	second_tick$?:second_tick$_T
}