import type { ServiceType } from '@menus/service-type-common'
import type { Coupon } from './Coupon.js'
import type { OrderStatus } from './OrderStatus.js'
import type { OrderMenuDetail_I } from './OrderMenuDetail_I.js'
export interface Order {
	ID:number
	OrderNumber:string
	SubTotal:number
	DeliveryCharge:number
	Total:number
	Tax_Rate:number
	Tax:number
	Driver_Tip_Percent:number
	Driver_Tip:number
	ServiceFee_Rate:number
	ServiceFee:number
	GrandTotal:number
	DeliveryAddressID:number
	PaymentMethodID:number
	CreditCardID:number
	OrderDate:string
	OrderDate_ISO:string
	ETADate:string
	ETADate_ISO:string
	ServiceType:ServiceType
	RestaurantID:number
	RestaurantName:string
	RestaurantTimezone:string
	RestaurantPhone:string
	RestaurantAddress:string
	Cuisine:string
	CuisineID:number
	Segment:string
	OrderStatusID:number
	OrderStatus:string
	RestaurantOrderStatusText:string
	ConsumerOrderStatusText:string
	FileName:string
	RestImageExist:boolean
	Discount:number|null
	PlatformCompanyID:number
	TotalRow:number
	TotalPages:number
	Coupons:Coupon[]
	AllowReview:boolean
	AllowChat:boolean
	IsReviewed:boolean
	MenuDetail:OrderMenuDetail_I
	StatusHistory:OrderStatus[]
	Apartment_Suite:string
	Braintree_Transaction_ID:string
	CustomerAddress:string
	CustomerCity:string
	CustomerID:number
	CustomerName:string
	CustomerPhone:string
	Date_Created:string
	Date_Deleted:string
	Date_Modified:string
	Date_Queue:string
	DeliveryAddress:string
	DeliveryMode:string
	DeliveryModeID:number
	Distance:number
	DrivingDistance:number
	ETA:number
	Enabled:boolean
	FireFlyID:string
	Instructions:string
	Is_Accepted:boolean
	Is_Cancelled_By_Customer:boolean
	Is_Cancelled_By_DeliveryCompany:boolean
	Is_Cancelled_By_Restaurant:boolean
	Is_Completed:boolean
	Is_Deleted:boolean
	Is_PreOrder:boolean
	Is_Queued:boolean
	Is_Read:boolean
	Is_Ready:boolean
	Is_Scheduled:boolean
	Is_Settled:boolean
	Is_Started:boolean
	OrderETA:string
	OrderSource:string
	OrderTimeDetails:string
	Owner_SubscriptionID:number
	PaymentMethod:string
	RestaurantID1:number
	ServiceFee_TransactionFee:number
	ServiceTypeID:number
	Status:string
	StatusID:number
	SubscriptionName:string
	Tax_Final:number
	Tax_State:string
	Tax_Zip:string
	TimeZone:string
	TimeZoneID:number
	ORDER_STARTED_ACTUAL:string
	ORDER_STARTED_ETA:string
	ORDER_READY_ETA:string
	ORDER_READY_ETA_UTC: string
	ORDER_READY_ACTUAL:string
	ORDER_COMPLETED_ETA:string
	ORDER_COMPLETED_ETA_UTC:string
	ORDER_COMPLETED_ACTUAL:string
	ORDER_COMPLETED_MINUTES:number
	TzOffsetMilliSeconds:number
}
