export * from './web_apigateway_b.js'
export * from './web_host_b.js'
export * from './web_lambda_function_b.js'
export * from './web_lambda_version_b.js'
export * from './web_root_distribution_b.js'
export * from './web_star_distribution_b.js'
