/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { main_dashboard_content$_T } from './CrMainDashboard/main_dashboard_content$_b.js'
import type { is_ProfileHandle_open$_T } from './is_ProfileHandle_open$_b.js'
import type { toggle_ProfileHandle_T } from './toggle_ProfileHandle_b.js'
export interface consumer_layout_ui_ctx_I {
	main_dashboard_content$?:main_dashboard_content$_T
	is_ProfileHandle_open$?:is_ProfileHandle_open$_T
	toggle_ProfileHandle?:toggle_ProfileHandle_T
}