export const aws_env:aws_env_T = process.env as unknown as aws_env_T
export interface aws_env_T {
	AWS_AZ:string
	AWS_REGION:string
	AWS_ACCESS_KEY_ID:string
	AWS_SECRET_ACCESS_KEY:string
	AWS_CERTIFICATE_ARN:string
	AWS_IMAGES_CERTIFICATE_ARN:string
	CDK_DEFAULT_ACCOUNT:string
	CDK_DEFAULT_REGION:string
	LOCAL_AZ_PAY_AWS_CERTIFICATE_ARN:string
	LOCAL_AZ_AWS_CERTIFICATE_ARN:string
	LOCAL_AZ_API_AWS_CERTIFICATE_ARN:string
	DEPLOY_INSTANCE_ID:string
	DEPLOY_INSTANCE_URL:string
	MENUSAPPBUILDER_INSTANCE_ID:string
	MENUSAPPBUILDER_VPC_ID:string
	MENUSAPPBUILDER_SUBNET_ID:string
	DEV_WAF_WHITELIST_IP_SET_ARN:string
	LIVE_WAF_WHITELIST_IP_SET_ARN:string
	DEV_MAPP_URL:string
	LIVE_MAPP_URL:string
}
