/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { default_userPayment$_T } from './default_userPayment$_b.js'
import type { userPayments$_T } from './userPayments$_b.js'
export interface user_payment_ctx_I {
	default_userPayment$?:default_userPayment$_T
	userPayments$?:userPayments$_T
}