/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { autoSuggestList$_T } from './autoSuggestList$_b.js'
export interface consumer_user_ctx_I {
	autoSuggestList$?:autoSuggestList$_T
}