/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { consumer_home_url__T } from './consumer_home_url__b.js'
import type { fireFlyID_url__T } from './fireFlyID_url__b.js'
export interface route_ctx_I {
	consumer_home_url_?:consumer_home_url__T
	fireFlyID_url_?:fireFlyID_url__T
}