/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { globalSettings$_T } from './globalSettings$_b.js'
import type { globalSettings_Subscription$_T } from './globalSettings_Subscription$_b.js'
export interface ro_user_ctx_I {
	globalSettings$?:globalSettings$_T
	globalSettings_Subscription$?:globalSettings_Subscription$_T
}